### ISSUE TITLE
Repository methods not working

### ISSUE THREAD

**Issue by bazo** [doctrine/mongodb-odm#1111]
```
/**
 * @ODM\Document(repositoryClass="Repositories\UserRepository")
 */
class User extends \AbstractUser implements \JsonSerializable {
...
/**
	 * @ODM\ReferenceMany(targetDocument="Membership", mappedBy="user", repositoryMethod="getCurrentMembership")
	 * @var type
	 */
	protected $membership;
}
```

adn the membership class
```
use Doctrine\ODM\MongoDB\Mapping\Annotations as ODM;

/**
 * @ODM\Document(repositoryClass="Repositories\MembershipRepository")
 */
class Membership extends Document {}
```

if I use the repository by itself like this
```
$repo = $dm->getRepository(\Membership::class);
dump($repo->getCurrentMembership($this->me));
```

i get the correct membership object.

but if i access it like 
```
$user->getMembership()
```

the repository method is not being called.

this is quite a serious issue for me. any way to fix this?

I have installed the latest @dev package from composer 

edit: had the method in wrong repository, but the custom method is still not being called

**Comment by malarzm** [comment]
@bazo can you please provide failing test case? [There are tests](https://github.com/doctrine/mongodb-odm/blob/5b30e0f7a677c8a7494d82176bb8a747f4e82fb9/tests/Doctrine/ODM/MongoDB/Tests/Functional/ReferenceRepositoryMethodTest.php) for using `repositoryMethod` and everything seems to be working fine ODM wise. Maybe the problem lies in `Document` class you are extending?

**Comment by malarzm** [comment]
Closing because of no response
