### ISSUE TITLE
Inverse-side PersistentCollections should be immutable

### ISSUE THREAD

**Issue by jmikola** [doctrine/mongodb-odm#1172]
This issue came out of #1086, where we discussed several edge cases when working with inverse-side PersistentCollections that have been modified.

> @jmikola: Should we consider documenting that inverse collections are read-only, or perhaps enforce that with a special PersistentCollection sub-class? AFAIK, changes to such a collection would not be reflected in the changeset (so they are already read-only from ODM's perspective). If users actually want to modify the collection (so their data model doesn't have to care), I suppose they can manually unwrap it in a lifecycle event and work with an ArrayCollection.
> 
> @alcaeus: I agree with having an ImmutablePersistentCollection class which forbids any write operations (`add()`, `clear()`, `remove()`, `removeKey()`, `set()`) in order to preserve the intended behavior. Only thing is, while it might be that we're just strictly enforcing something that was an unwritten rule before, we're technically breaking BC here.

**Comment by malarzm** [comment]
>  I suppose they can manually unwrap it in a lifecycle event and work with an ArrayCollection.

What about having additional parameter in mapping to unwrap it automatically? Lifecycle event seems to be too much compared to `@ReferenceMany(..., immutable="false")`

Anyway I still have in mind introducing custom collections so I'd say create a (really) Big Red Warning in the docs (not current notice, a Big Red Warning) to not complicate things in future?

**Comment by malarzm** [comment]
For the record from IRC:

> @alcaeus: @Ocramius had some input on that one as well
basically, the recommendation at the time was to have PersistentCollection be mutable to allow people to add items to inverse collections before persisting to the database - well knowing that some counts _may_ be off if they do
ORM has the same issue we do. personally, i don't like removing functionality from a class, which is why i could live with leaving PersistentCollection fully mutable as long as we document this somehow

**Comment by dossorio** [comment]
+1 for flexibility and freedom of immutable="false" ! 

I guess in bi-directional relations like Task <-> Tag where tags are reusable among the Tasks is ok, but in (for example) Task <-> Comment, I would like to delete comments from inside comments Task collection.

As you were discussing, its quite confusing, the fact that you can call remove() on a PersistentCollection and it is not persisted, because is the inverse-side of the relation.

Anyway, I hope I understood everything well ! It took me a while and I feel I don't know even a half ! :)

Thanks !!

**Comment by malarzm** [comment]
Custom collections are implemented for a while now, whoever wants immutability for inverse side of references can employ them :)
