### ISSUE TITLE
Deprecate field type annotation classes in favor of Field

### ISSUE THREAD

**Issue by jmikola** [doctrine/mongodb-odm#1207]
This is related to #1168 (deprecating annotations that share names with reserved words in PHP7). It is more directly related to doctrine/phpcr-odm#641 and the corresponding PR (doctrine/phpcr-odm#643).

We should encourage users to use `@Field(type="...")` instead of the plethora of named annotation classes. Deprecating this in 1.x will allow us to remove the named classes entirely in 2.0.

**Comment by Bilge** [comment]
This is terrible! Not just that you're deprecating a longstanding mainstay of the annotation API, not just that a deprecation notice has already been merged warding people away from it but *mostly* because the major motivating factor &ndash; that four of the class names clash with PHP 7 reserved words &ndash; is an entirely artificial constraint!

Whilst it may be true that you can no longer call a class *Bool* or *String*, the 1:1 mapping between annotation types and class names is entirely artificial and if it needs to be changed then it *can* and *should* be. A custom mapping between annotation names and class names should be added for the classes affected by the introduction of reserved words in order to preserve the existing API. The introduction of PHP reserved words need not directly affect users of ODM.

**Comment by alcaeus** [comment]
As I have just mentioned in IRC, you are welcome to open a ticket for this in [the annotations project](https://github.com/doctrine/annotations) as that is where the limitation comes from.
