### ISSUE TITLE
createQueryBuilder pagination not working

### ISSUE THREAD

**Issue by pablomoreno61** [doctrine/mongodb-odm#1226]
I'm executing the following instruction:

    $blogPosts = $this->dm->createQueryBuilder('User')
    ->limit(10)
    ->skip(5)
    ->getQuery()
    ->execute();

I'm expecting just 10 results, but this is giving me all the results without any pagination. Am I missing something or there is something wrong with skip, limit and ODM?

**Comment by malarzm** [comment]
@pablomoreno61 limit and skip should be applied to Cursor according to https://github.com/doctrine/mongodb/blob/556287acc8020c5dd0042c6c150c845fdbf9458b/lib/Doctrine/MongoDB/Query/Query.php#L398-L400 which is called by https://github.com/doctrine/mongodb-odm/blob/c3933ad5eb0c23e7262f60efa1ad12605484bf48/lib/Doctrine/ODM/MongoDB/Query/Query.php#L296. Would you mind creating failing test case?

**Comment by alcaeus** [comment]
@pablomoreno61 One more question about this: did you call ```toArray()``` and got more than 10 items or did you call ```count()``` on the cursor and it returned a value greater than 10?

I'm asking because cursors in MongoDB by default don't count found elements but all elements, see the [MongoCursor documentation](https://secure.php.net/manual/en/mongocursor.count.php). This is reflected in ODM as well. Elaborating on your example above:
* ```$blogPosts->toArray()``` should return 10 items at most
* ```$blogPosts->count()``` should return the number of all items that are found using the query (without applying skip and limit options
* ```$blogPosts->count(true)``` should return a value less than or equal to 10, depending on how many items are present.

**Comment by alcaeus** [comment]
@pablomoreno61 do you have an update on this?

**Comment by pablomoreno61** [comment]
I didn't has time to test it until now. @alcaeus I've tested your solution and it works perfectly. Many thanks to all of you!

**Comment by pablomoreno61** [comment]
Just a question, how it works the doctrine cache in this case?

**Comment by malarzm** [comment]
Sorry, just noticed the question: what do you mean by doctrine cache? ODM doesn't use any out of the box, the only "cached" things may be already hydrated documents that will be returned instead of re-hydrating or when asking for a document by an identifier.

Closing issue for now.
