### ISSUE TITLE
Could we get a lifecycle callback for missing proxy objects?

### ISSUE THREAD

**Issue by sharpner** [doctrine/mongodb-odm#1258]
It would be awesome If I could gain control over this situation:
```The "Proxies\__CG__\Some\Example\Document“ document with identifier "511111111111111110000000“ could not be found.```

For example in a RefMany Scenario were only 5 of 6 Items are still available: 
By using a callback like "onMissingReference()" I could return an empty document with some default text that would explain it. like "Deleted". 

Currently my application simply crashes, the scenario is similiar to a null->getName() :(

I think the PR #532 tried to implement it.

**Comment by alcaeus** [comment]
It looks like #532 can be re-used (apart from the comments in the original PR), but I'd hold off until #1331 is merged to avoid any conflicts.

Note that this will only work with a lifecycle event, not a lifecycle callback.
A lifecycle callback on the proxy object doesn't make much sense since it would possibly be an incomplete object and we really shouldn't call anything on it. A lifecycle callback on the owning object is a bit complicated since a proxy object might be shared between multiple owning documents and all would have to be notified. Without a sensible way of tracking object usage this isn't possible.

**Comment by malarzm** [comment]
@alcaeus just merged #1331 to not hold you back (and me on collections as well) ;)
