### ISSUE TITLE
suggest username available from mongodb using symfony2

### ISSUE THREAD

**Issue by wajaja** [doctrine/mongodb-odm#1282]
I use FOSUserBundle; I want that when a user enters an existing username; it has a username list available

**Comment by malarzm** [comment]
@wajaja and how exactly ODM can help you?

**Comment by smolinari** [comment]
If I my guess of is right, he is looking for an autofill or autocomplete like this.

https://jqueryui.com/autocomplete/

Scott

**Comment by wajaja** [comment]
@malarzm ;  i would like this: 
before creating a user; make a query the database to get the username list available whose names correspond to the one introduced by the user; Then he suggested the username by adding a number of order.

example: if cedrickngeja are suggested cedrickngeja1, cedrickngeja2, cedrickngeja6

**Comment by malarzm** [comment]
@wajaja I get the idea but how is this anything for ODM itself? :) If we'd be to ship something like this it'd be in [bundle](https://github.com/doctrine/DoctrineMongoDBBundle) since it's Symfony related but we can't since desired format depends on frontend tool you might want to use. Such things are supposed to be crafted per project by developers, at least in my opinion.

**Comment by smolinari** [comment]
Ah, that isn't the same as what I thought you meant and definitely has nothing to do with ODM.

Scott

**Comment by malarzm** [comment]
Closing since there's nothing we can do.
