### ISSUE TITLE
Wrong cursor count when priming enabled

### ISSUE THREAD

**Issue by metanav** [doctrine/mongodb-odm#1283]
It works as expected when priming is not used at all. It's happening after upgrading from 1.0.0-BETA13 to 1.0.3.

**Comment by malarzm** [comment]
@metanav how exactly does your query look like? Form top of my head primed query are eager now by default (as of 1.0.0 I believe) but that shouldn't break anything

**Comment by metanav** [comment]
@malarzm, I am doing query as follows:
```
$qb = $this->dm->createQueryBuilder('Document\Group');
$qb->field('community')->prime(true);
$results = $qb->getQuery()->execute();
return new \Zend\Paginator\Paginator(
    new \DoctrineMongoODMModule\Paginator\Adapter\DoctrinePaginator($results)
);
```

**Comment by alcaeus** [comment]
It won't break anything. However, ```count``` functionality is different for eager vs. non-eager cursors.

By default, ```count``` for a cursor counts all items in the collection queried, not only those found. To get the number of results returned by the cursors, one must set the ```$foundOnly``` parameter to true in ```count()```.
With eager cursors however, there is no such distinction and the ```count()``` method will always return the number of results returned by the cursor (it implies ```$foundOnly = true```).

With 1.0.0 we decided to change priming functionality and move priming to the cursor (so the primers are only called when iterating the results for the first time, not directly after query execution). In order to improve performance of this feature, priming implies an eager cursor to avoid re-running the query when iterating results after the priming run. This might explain the difference you are experiencing with BETA13 vs. 1.0.3.

**Comment by metanav** [comment]
Yes, I am getting the total_items count (returned by Paginator::getTotalItemCount() which eventually calls Cursor::count()) same as page_size count. What's the issue?

**Comment by alcaeus** [comment]
Calling ```prime(true)``` implies ```eagerCursor(true)```. With eager cursors, all items eventually returned by the cursor are fetched when the cursor is opened. This is done to prevent multiple calls to the database by one cursor: when iterating a cursor twice the query is actually run twice; with eager cursors it is only run once. Also, when calling ```count()``` it will return the number of items it has cached, which respects the ```limit``` option set on the cursor. This is a limitation of eager cursors.

Why does priming enforce an eager cursor? For one, since priming iterates the cursor once the query would always be run at least twice (once for priming and once when the user is actually using the results). Another reason is that the result might have changed between priming and when the user is iterating, so it might return different results than before. To avoid this we decided to enforce eager cursors when using primers.

**Comment by metanav** [comment]
What I have understood by your detail explanation, the cursor fetches documents when paginator starts iterating and primers are fetched eagerly which changes the count of the cursor which is now the number of primed documents. Is there any way to get the original total items count?

**Comment by alcaeus** [comment]
Yes, either do away with priming (which probably isn't an option), or run a separate count query to get number of all results.

**Comment by metanav** [comment]
Yes, I have to stick with priming (no option). I can cache the value of count($qb->getQuery()->execute()) before passing it to the Paginator but the problem is it's DoctrinePaginator class which calls the Cursor::count() not my code and it would be an overhead to create my own paginator to get the right count. Any thoughts?

**Comment by alcaeus** [comment]
How about a data object that holds results and total result count as properties? That would allow you to intercept all calls to ```count()``` made by the paginator and return the proper result. You'd have to re-implement iterator functionality and pass it along the underlying cursor but it would work...somehow ;)

**Comment by malarzm** [comment]
Also there's an idea to tweak Paginator (especially since it's Doctrine module) and make it do the workaround if EagerCursor is detected

**Comment by metanav** [comment]
I think it would be great to tweak the DoctrinePaginator. Shouldn't we mark it as a BC break?

**Comment by malarzm** [comment]
> Shouldn't we mark it as a BC break?

This was introduced in 1.0.0 (however it's a bit unfortunate it landed in [Performace section](https://github.com/doctrine/mongodb-odm/blob/master/CHANGELOG-1.0.md#performance-optimizations) of change log given its side effect) when we had to break some things - not sure if we can do anything more about it, surely we'll be more cautious with next releases especially we're no longer in BETA :)

**Comment by metanav** [comment]
@alcaeus I extended Paginator class and which returns  the total items count preset by the results count not from the Cursor::count() so the final response have the real total items count. But the EagerCursor::skip is not calling Cursor::skip() but Cursor::limit() which is breaking the Paginator behavior again. My question is: can't we make EagerCursor optional for priming? I understand it improves the performance but if paginator is not working how can we use it in real world scenario?

**Comment by alcaeus** [comment]
*sigh* yes, I remember. doctrine/mongodb#229 has been merged, I'll try to tag a release later today.

As for making EagerCursor optional, that is not an option. You can see what happens when we prime without EagerCursor by looking at #1108.

**Comment by metanav** [comment]
Thanks, I can wait for the release. For now I have changed it locally and pagination seems working fine. 
One another problem I encountered now. While testing it on a big collection, around 1,400,000 documents, it exited with the following error:

"Fatal error: Allowed memory size of 4294967296 bytes exhausted (tried to allocate 32 bytes) in vendor/doctrine/mongodb/lib/Doctrine/MongoDB/Cursor.php on line 460"

You can see I have already allocated 4GB memory to php and should be sufficient for most of the extreme cases. When I disabled priming, it just worked.  The query is given below:
```
$qb = $this->dm->createQueryBuilder('Document\Group');
$qb->field('community')->prime(true);
$results = $qb->getQuery()->execute();
return $results->count();
```
I am assuming only counting doesn't try to fetch all reference primed.

**Comment by alcaeus** [comment]
I'm afraid I have to disappoint you here as well. EagerCursors do one call to the database only, which is to fetch all available data. After that the cursor no longer needs the database. This means that using a reference primer without limit all results from the query will be fetched and kept in memory.

**Comment by metanav** [comment]
But the priming only triggers when cursor starts iterating. Does count() iterate the cursor?

**Comment by alcaeus** [comment]
Priming only triggers when the cursor starts iterating. However, when doing a count or starting the iteration, an eager cursor fetches all data from the database and stores it internally, see https://github.com/doctrine/mongodb/blob/master/lib/Doctrine/MongoDB/EagerCursor.php#L118..L124. This happens regardless of primers (even when primers are disabled one could use an eager cursor).

It is the eager cursor causing your memory exhaustion, not primers.

**Comment by metanav** [comment]
I see. I didn't realise that EagerCursor converts the cursor to array. I also think that switching to non-eager base cursor during pagination would solve this. Thanks for you time!

**Comment by alcaeus** [comment]
@metanav doctrine/mongodb 1.2.1 was just released, your skip/limit issue should be fixed now.

**Comment by alcaeus** [comment]
Closing this as it's not an issue with ODM but rather the paginator implementation tracked in the module repository.
