### ISSUE TITLE
Embeds gets duplicated in a cloned, referenced document

### ISSUE THREAD

**Issue by nclavaud** [doctrine/mongodb-odm#1308]
Not sure this is a bug or unexpected behavior - this might as well be a tricky use-case on our side - but we've thought we will submit an issue anyway.

We get persisted duplicates on the following use case: consider a `Group` document that embeds a collection of `Topic` documents (`$group->topics`). If we clone `Group` and add it as a reference in a `User` document (`$user->groups->add(clone $group);`) then embedded `$group->topics` will be duplicated (and the cloned group will not be persisted).

However, if we manually set the ID of the cloned group to `null`, then everything seems to work as expected. But I can't find anything in the documentation about the need to reset the ID after cloning.

Duplication started to occur with commit a24e73c3377d31486f92ddfa3c34814c0e575e7a. Below is a test case that passed before this commit.

```php
<?php

namespace Doctrine\ODM\MongoDB\Tests\Functional\Ticket;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ODM\MongoDB\Mapping\Annotations as ODM;

class GH20151215Test extends \Doctrine\ODM\MongoDB\Tests\BaseTest
{
    public function testDuplicatedEmbeds()
    {
        $group = new GH20151215Group();
        $group->topics->add(new GH20151215Topic('Science'));
        $this->dm->persist($group);
        $this->dm->flush();

        $group2 = clone $group;
        // $group2->id = null;

        $user = new GH20151215User();
        $user->groups = new ArrayCollection(array($group2));

        $this->dm->persist($user);
        $this->dm->flush();
        $this->dm->clear();

        $user = $this->dm->find(get_class($user), $user->id);

        $this->assertCount(1, $user->groups->first()->topics);
    }
}

/** @ODM\Document */
class GH20151215User
{
    /** @ODM\Id */
    public $id;

    /** @ODM\ReferenceMany(targetDocument="GH20151215Group", cascade="persist") */
    public $groups;

    public function __construct()
    {
        $this->groups = new ArrayCollection();
    }
}

/** @ODM\Document */
class GH20151215Group
{
    /** @ODM\Id */
    public $id;

    /** @ODM\EmbedMany(targetDocument="GH20151215Topic") */
    public $topics;

    public function __construct()
    {
        $this->topics = new ArrayCollection();
    }
}

/** @ODM\EmbeddedDocument */
class GH20151215Topic
{
    /** @ODM\Id */
    public $id;

    /** @ODM\String */
    private $name;

    public function __construct($name)
    {
        $this->name = $name;
    }
}
```

**Comment by alcaeus** [comment]
There are two things coming in to play here: Part 1 is the cloning of the Group itself.
When encountering an object not in the list of managed objects, UnitofWork tries to persist it to the database. This is treated like a regular insert *unless an ID has been specified*. In that case, it will treat it as an upsert, meaning any existing documents with the same ID will be overwritten. Solution: as you noticed, remove the ID when cloning and it will work fine.

Part 2 concerns embedded documents. You have to know that embedded documents (unlike referenced documents) can only belong to one parent document. Previously, when cloning a document, the developer was in charge of deep-cloning embedded documents. This continuously had [some](https://github.com/doctrine/mongodb-odm/issues/1229) [strange](https://github.com/doctrine/mongodb-odm/issues/1169) [side](https://github.com/doctrine/mongodb-odm/issues/478) [effects](https://www.youtube.com/watch?v=dQw4w9WgXcQ). In order to resolve that, starting with 1.0.3 the behavior changed as was described in [the release blog post](http://www.doctrine-project.org/2015/11/03/doctrine-mongodb-odm-release-1-0-3.html): when UnitOfWork encounters an embedded document that belongs to another document, it will clone the embedded document and store that.

From what I can see, the behavior you are experiencing is exactly as it should be.

**Comment by nclavaud** [comment]
Thank you very much for your quick answer.

> Solution: as you noticed, remove the ID when cloning and it will work fine.

Shall we document this somewhere? Maybe on [Working with objects](http://docs.doctrine-project.org/projects/doctrine-mongodb-odm/en/latest/reference/working-with-objects.html)?

> when UnitOfWork encounters an embedded document that belongs to another document, it will clone the embedded document and store that

It seems that the UoW is cloning indeed, even if the cloned parent document and original parent document have the same identity.

**Comment by malarzm** [comment]
> It seems that the UoW is cloning indeed, even if the cloned parent document and original parent document have the same identity.

ODM (and ORM as well) is relying on fact that document with same identity has exactly one instance hence check `$currentParent === $knownParent` was sufficient :)

**Comment by nclavaud** [comment]
Fair enough. Thank you, I'm closing this.
