### ISSUE TITLE
ODM embedOne multiTypes documents

### ISSUE THREAD

**Issue by SpencerZ** [doctrine/mongodb-odm#1327]
What I want to do:
1.  create Log, Log data dictionary is
```
/**
* @ODM\Document
*/
class Log {
  /**
  * @ODM\EmbedOne
  */
  protected $desc;
}
```

2. desc may embed different embeddedDocument, before this time, I only know embed one targetDocument, not know how to embed a document regardless of class type

so I read the doctrine odm documentation, found the inheritance mapping, this help me to make it.

* define a base class, define it as follows
```
/**
* @ODM\Document
* @ODM\InheritanceType("SINGLE_COLLECTION")
* @ODM\DiscriminatorField("type")
* @ODM\DiscriminatorMap({"type1"="type1LogDescClass"})
*/
class BaseClass
```
**DiscriminatorField** is an attribute of extend class, which we can define the map of it and extend class in **DiscriminatorMap**
* define the extend class what you want to save to desc
```
/**
* @ODM\EmbeddedDocument
*/
class type1LogDescClass extends BaseClass
```

successfully!

**Comment by alcaeus** [comment]
After reading multiple times I fail to see a question in there. I'll try to dissect: the `BaseClass` mapping is incorrect since it should specify `@ODM\EmbeddedDocument` instead of `@ODM\Document`.
Then, in the mapping for the `$desc` field, specify a targetDocument to get ODM to use the discriminator map specified for `BaseClass`:
```
/**
 * @EmbedOne(targetDocument="BaseClass")
 */
protected $desc;
```

If you don't specify a target document, you'll have to specify a `discriminatorField` and (optionally) `discriminatorMap` property on the `EmbedOne` annotation.

**Comment by SpencerZ** [comment]
@alcaeus 
sorry I didn't write clearly. The question is although I create document correctly successfully, but I think these code are not write correctly, so I want to know how to improve it. Thank u!
