### ISSUE TITLE
using doctrine to map "raw" data

### ISSUE THREAD

**Issue by wgallagher** [doctrine/mongodb-odm#1350]
We're increasingly seeing the need to map data that's coming from backends that doctrine doesn't support.  For example, dynamodb and REST services.  I was wondering if there is any support in Doctrine for mapping raw PHP Arrays to / from models.  If not, has anyone considered adding it?

**Comment by malarzm** [comment]
@wgallagher possibly there is an exact match - [a raw type](https://github.com/doctrine/mongodb-odm/blob/master/lib/Doctrine/ODM/MongoDB/Types/RawType.php) :) I'm even using it in our application to save raw json values sent from API (and return them later as it's namely for saved search criteria)

> the need to map data that's coming from backends that doctrine doesn't support

What exactly we don't support? Maybe it'll be common enough to add to core

**Comment by wgallagher** [comment]
Support for a REST backend would be very useful to us as would a DynamoDB backend.

For REST, we're replacing some of our mongo mappings with calls to REST services.  So, for example, instead of looking up a mongo record by ID, we're making a rest call with an ID:

http://host:port/api/users/12345

And that returns a json object representing the record.  We'd like to be able to hydrate doctrine models with the json.  In addition, we'd like to be able to take a Doctrine model and serialize it into an array containing a changeset or a complete document.

**Comment by malarzm** [comment]
You can take a look at #1348 but also to answer your questions here:

> We'd like to be able to hydrate doctrine models with the json.

You can already use Hydrators for that given json is converted to an array (https://github.com/doctrine/mongodb-odm/pull/1348#issuecomment-174084190)

> take a Doctrine model and serialize it into an array

That's actually not Doctrine's responsibility, we're persisting stuff, not serializing it :) JMSSerializer is good for that

**Comment by speedytwenty** [comment]
Thought I'd go ahead and add my question to this thread as it is very similar.

I am hydrating a document from data retrieved from a REST API and attempting to persist it to the database. The documents' mappings are identical with the exception of the "_id". The rest api uses it's own id key for which I am using alsoLoadMethods to map the "source id key" to the mongo id (_id). This is working fine, I only mention this as this difference in mapping prevents me from using the UnitOfWork::getOrCreateDocument() method.

I am using the merge() method instead of persist().

The problem I am having is that embedded documents are not being saved to the database. It seems these are "lazily loaded" and not "initialized" after hydration.

Is there a way to dynamically force all lazily loaded fields to be initialized for a document? Or is there perhaps another route that you recommend for what I am doing?

Here is some pseudo code that portrays what I'm trying to do:
`
$response = API::get('some/remote/path');
$data = json_decode(json_encode($response), TRUE);
$document = $metadata->newInstance();
$documentManager->getHydratorFactory()->hydrate($document, $data);
$documentManager->merge($document);
$documentManager->flush();
`

Any help or insight is very much appreciated!

**Comment by malarzm** [comment]
@speedytwenty you're hit by the same thing that bit me and for which I created https://github.com/doctrine/mongodb-odm/pull/1403. Given you're running `dev-master`, once you change your code to

```
$documentManager->getHydratorFactory()->hydrate($document, $data, [ Query::HINT_READ_ONLY => true ]);
```

it should all work. If above solution works for you but you don't want to run `dev-master` please wait till the end of the week as little bird tells me we'll cut a release by then :)

Long story short, thanks to the `READ_ONLY` hint ODM will not register any embedded documents it encounters during hydration thus later persisting will calculate change sets for them properly.

**Comment by speedytwenty** [comment]
@malarzm Thanks for the response! This seems to be exactly the fix I am looking for, except it only seems to work for "embedOne" and not for "embedMany". Perhaps I'm missing something. Any ideas?

**Comment by malarzm** [comment]
Hmmm theoretically `embedMany` should work just fine, that's even included in a [test case](https://github.com/doctrine/mongodb-odm/blob/f88851d2269c4b79b34271dedf4f8a0b7f72edfe/tests/Doctrine/ODM/MongoDB/Tests/HydratorTest.php#L63)... Would you mind creating failing test and send it as a PR?

**Comment by speedytwenty** [comment]
Thanks again for the support on this!

I have added a functional test which fails for embedMany and submitted a PR: #1418

**Comment by malarzm** [comment]
To sum things up:

> any support in Doctrine for mapping raw PHP Arrays to models.

You can hydrate models with your own data and additionally (since 1.1) there's `READ_ONLY` hint to ensure the model stays out of ODM until merge (see #1403 for more info)

> any support in Doctrine for mapping raw PHP Arrays from models.

It's not really our responsibility however this MAY change in 2.0 if couple other things work as planned (but do not expect full blown serializer, it'll be something small tailored to our persistent-related needs)
