### ISSUE TITLE
Expr's implementation of equals overwrites other conditions or is itself overwritten by them.

### ISSUE THREAD

**Issue by josefsabl** [doctrine/mongodb-odm#1361]
Code like this:

	$queryBuilder
		->field('myField')->equals('456')
		->field('myField')->in(['123', '234']);

Should obviously generate query like this:

	query => array (2)
		myField => array (1)
			"$eq" => "456" (3)
			"$in" => array (2)
				0 => "123" (3)
				1 => "234" (3)
		
Instead it throws away the first condition. Probably because it uses the shorthand syntax, overwriting the value in an array. Like this.

	query => array (2)
		myField => array (1)
			"$in" => array (2)
				0 => "123" (3)
				1 => "234" (3)

**Comment by josefsabl** [comment]
The problem seems to be in Expr class in the method

	public function equals($value)
	{
		if ($this->currentField) {
			$this->query[$this->currentField] = $value;
		} else {
			$this->query = $value;
		}
		return $this;
	}

That obviously overwrites query fields. It should instead look like:

	public function equals($value)
	{
		return $this->operator('$eq', $value);
	}

Unfortunately, there is no way to skip the broken Builder->equals() method and write something like Builder->expr->operator("$eq", $value).

**Comment by josefsabl** [comment]
The best workaround I found is: Instead of:

		$queryBuilder->equals($value);
		
Use:

		$expression = $queryBuilder->expr();
		$expression->field($field)->operator('$eq', $value);
		$queryBuilder->addAnd($expression);

Two problems:

1. The workaround introduces the $field variable potentially breaking encapsulation.
2. How will it affect performance?

**Comment by alcaeus** [comment]
Note: this issue actually affects [doctrine/mongodb](https://github.com/doctrine/mongodb) since that's where the `Expr` class comes from. Having said that, this is a bit more complicated than just "not overwriting a query". Take the following query:
```
        $expr
            ->field('myField')->equals('456')
            ->field('myField')->gt('123');
```

In this case, we will try to preserve the equality match and produce the following query array:
```
[
    'myField' => [
        '$in' => ['456'], 
        '$gt' => '123'
    ]
]
```

When a field has an equality query condition that does not use the `$eq` operator, we wrap it into an `$in` operator with one element. This is done because the `$eq` operator is not supported on all server versions. This works well until you bring a second `$in` query into the mix. What should the resulting query array look like? Should the `$in` queries be combined, implicitly producing an `$or` query instead of the `$and` one would expect? Should the second `$in` operator be ignored? Should the original equality match be discarded?

If you write the query in one method I'd suggest avoiding producing a query like this. If you're programmatically building the query I would suggest working with expressions:
```
$equalityMatch = $queryBuilder->expr()->field('myField')->equals('456');
$inMatch = $queryBuilder->expr()->field('myField')->in(['123', '234']);

$queryBuilder
    ->addAnd($equalityMatch)
    ->addAnd($inMatch);
```

**Comment by josefsabl** [comment]
Answer to your question about second `$in` is easy. Both `$in` should be applied as intended by user. Doctrine should not try to be more clever than user. Of course that when I do:

	$expr
		->field('myField')->in(['123'])
		->field('myField')->in(['345']);

I should get:

	[
		'myField' => [
			'$in' => ['123'], 
			'$in' => ['345']
		]
	]

Does a query like that make practical sense? Doctrine really should not care. User explicitly demands to return all documents that match two expressions. None of document does and that result should be empty set.

What will SQL query like this return?

	SELECT * FROM user WHERE name = "john" AND name IN ("jack")

Zero results of course. Nobody will dispute that (I hope).

Doctrine just throws the first condition away. Of course it does, you say, because it doesn't make sense and silly user must have had put it in there by accident, so let's just ignore it.

This behavior is misleading, buggy and potentially VERY dangerous. Imagine authorization system built on top of this!

Yes, of course we build the query programmatically. So you say there is another method, or let's say syntax, that will work as expected? Well that makes me ask why is there a documented syntax, seemingly equivalent, that does not work as expected. In other words by providing this "It doesn't work? Well then do it the different way." suggestion you are just confirming that the bug is there.

If this is in the wrong repo. Okay, let's move the issue. But you can't be serious about dismissing it as okay only because of the internal implementation restrictions don't somehow allow for it to be correct.

PS: Don't want to sound rude or angry or anything. But I really feel heavily frustrated at the moment.

Cheers :-)

**Comment by alcaeus** [comment]
I'm sorry you feel I'm dismissing this as okay. Let me try to explain the reasoning behind the change (wrapping equality conditions into `$in`):

Let's say you have the following statement:
```
$queryBuilder
    ->field('myField')
    ->equals('something')
    ->gt('foo');
```

After the call to `equals`, the query array looks like this:
```
[ 'myField' => 'something' ]
```

We cannot use the `$eq` operator here since that is new in MongoDB 3.0 and we want to support older releases of MongoDB as well. Normally, this won't matter but it becomes a problem once the next operator comes in since we have nowhere to put the `$gt` operator. That's why we "cheat" and use the `$in` operator to change the query to this:
```
[
    'myField' => [ '$in' => ['something'] ]
]
```

Now we add the `$gt` operator to the query:
```
[
    'myField' => [
        '$in' => ['something'],
        '$gt' => 'foo'
    ]
]
```

As you can see, this works fine and it will work fine for all operators, **except `$in`**.

Now, let's say you create this query:
```
$queryBuilder
    ->field('myField')
    ->in(['something'])
    ->in(['somethingElse']);
```

What's the result you expect? The example you provided won't work as PHP doesn't support it (you can't have two array items with the same key). So, in order not to be smarter than the user, we always keep the same value. This goes for every operator:
```
$queryBuilder
    ->field('myField')
    ->gt(1)
    ->gt(2)
    ->gt(3);
```

will leave you with
```[
    'myField' => [
        '$gt' => 3
    ]
]
```

The query builder doesn't throw the first operator away because "silly user must have had put it in there by accident, so let's just ignore it". The query builder throws it away because it can't know what exactly the user is trying to do and can only have one of each operator per field. You can mix and match operators but you can't have two `$gt` operators on the same field in the same expression. It just doesn't work. Go ahead and run this query in the mongo shell and look at the result:
```
db.test.insert({foo: 1});
db.test.insert({foo: 2});
db.test.count({foo: { $gt: 0, $gt: 1}});
```

So, let's look at the facts:
1. When there is an equality check on a field, it has to be wrapped to be using an operator when another check is added to the field
2. The `$eq` operator cannot be used because it's not supported on MongoDB < 3.0 which are still supported by ODM
3. To work around this, we use the `$in` operator.
4. In a query, each operator may only appear once per field. This is a limitation of arrays, BSON objects and pretty much every other data structure.
5. To resolve this issue, subsequent calls to `in`, `gt`, `equals` and other comparison operators discard previously set values.

All of this comes down to the workaround I gave before: use the `$and` operator to combine these queries:
```
[
    $and: [
        [
            'myField' => [ '$in' => ['something'] ]
        ],
        [
            'myField' => [ '$in' => ['somethingElse'] ]
        ]
    ]
]
```

This is not a workaround because we don't want to fix it. This is the only way you can actually write a query like this for MongoDB.
