### ISSUE TITLE
PHP7 compliance: annotation classes sometimes use reserved names

### ISSUE THREAD

**Issue by Pherserk** [doctrine/mongodb-odm#1368]
The name of some of the annotations e.g. "String", "Boolean" are considered reserverd words in php7, so them cannot be used to name a class:
http://php.net/manual/en/reserved.other-reserved-words.php

If is intended to support PHP7, I can start working to this fix.

**Comment by alcaeus** [comment]
Hi! Thanks for the offer - we have indeed taken care of this already: #1205 prevents importing the annotation classes that use reserved words - so if you use `@String` somewhere it would fail because the annotation class was not found. To be consistent across our mappings and with ORM, #1318 deprecates all type annotations (e.g. `@String`, `@Int`) and replaces them with `@Field(type="string")`. This is what you should use for PHP 7.

**Comment by ProntoPro** [comment]
Thank you so much for the help!
