### ISSUE TITLE
ReferenceOne by document field

### ISSUE THREAD

**Issue by fabiorphp** [doctrine/mongodb-odm#1491]
Guys, I found nothing about ReferenceOne with another document field instead of ID.

Is there any possibility that associate a document with another field instead of id, like slug for example?

**Comment by malarzm** [comment]
Not really, ID is the only one because it's guaranteed to be unique and is immutable. You'd need to use your slug as an identiefier.

**Comment by pvgomes** [comment]
@malarzm Make sense that lock in ID but sometimes We'd like use another field and continue using MongoDB object id as a "Primary Key", otherwise if we change our slug as a identifier the field in mongo change to "_id". 
Will be great if Doctrine use another fields as a identification with documents because we can bring flexibility with objects and clearly data inside documents.

We are creating that functionality and if you'll like, we can make a Pull Request in the future.

**Comment by malarzm** [comment]
Why won't you use `ReferenceOne` and combine it with `repositoryMethod`?

I'm not convinced that identifying documents by something else than an identifier is good idea, not only because of referential integrity (a theoretical one of course) but also because of `UnitOfWork` and proxies are relying on identifiers being the real identifiers. Also having two identifiers feels redundant :)

**Comment by alcaeus** [comment]
By definition, documents in MongoDB always have their primary key in `_id` (see [the documentation](https://docs.mongodb.com/manual/core/document/#the-id-field)). Because of the implied uniqueness, this is the logical choice. Furthermore, the [MongoDB documentation on references](https://docs.mongodb.com/manual/reference/database-references/) clearly specifies using the value from the `_id` field in manual references (`STORE_AS_ID` in ODM) as well as DBRef references. I see no reason to deviate from this standard.

There is nothing preventing you from adding another unique field (e.g. `slug`) and treating it like a primary key. It's just that MongoDB and Doctrine ODM will never see it as such.

**Comment by pvgomes** [comment]
Ok guys, sounds reasonable for us, after more research we agree about this. Thanks!
