### ISSUE TITLE
Setting "repositoryMethod" on "referenceMany" breaks persistence

### ISSUE THREAD

**Issue by Jan0707** [doctrine/mongodb-odm#1492]
Good day everyone,

I have stumbled across this issue and was wondering whether I have encountered a weird edge case / a bug or a feature:

When I set a custom repository Method on a reference many field in order to populate the hydrated collection everything works as expected.

However when I then modify that collection like this (pseudo code):

```
$newReferencedObject = new Object();
$dm->persist($newReferencedObject);
$hydratedDocument->getField()->add($newReferencedObject);
$dm->flush();
```

The new object is persisted, but the collection not updated. Everything seemed to work perfectly fine, until I introduced the "repositoryMethod" setting.

Any idea why that would happen ?

**Comment by Steveb-p** [comment]
I'm not sure, since I'm not ODM expert, but you might be running into a case where change tracking fails on object return from `getField()`. A similar case can be sometimes observed in ORM, when you try to update a `DateTime` instance and changes are not reflected during `flush()`, since it is still the same `DateTime` object and by default - as much as I'm aware - Doctrine just compares if it is still the same instance of the object.

See http://docs.doctrine-project.org/projects/doctrine-orm/en/latest/reference/change-tracking-policies.html.

However, I might be completely wrong on this ;)

**Comment by malarzm** [comment]
IIRC using the `repositoryMethed` marks collection as the inverse side thus no changes are saved to the collection itself (even it's existance in db should be ignored)
