### ISSUE TITLE
check for DocumentNotFound before it throws

### ISSUE THREAD

**Issue by caiquecastro** [doctrine/mongodb-odm#1511]
I have a document DocumentA that ReferenceOne(targetDocument="DocumentB", storeAs="id"):

```
  /**
     * @ReferenceOne(targetDocument="DocumentB", storeAs="id"
     */
    private $documentB;
```

If the documentB, that was referenced on the documentA, was removed, when I try to getDocumentB(), should it throw a DocumentNotFoundException? But it doesn't.

It only throws this exception if try to get some property on the document, for example:

```
// $documentA is an instance of DocumentA
$documentB = $documentA->getDocumentB(); // it returns an instance of DocumentB, with all its properties as null.
$name = $documentB->getName(); // it throws the DocumentNotFoundException.
```

Is this the expected behavior?

**Comment by alcaeus** [comment]
Yes, this is expected. When you have a reference, it's created as a proxy object unless it was already found in memory. The document is only loaded from the database when you first access a property or method of it. This helps to avoid unnecessary database reads.

**Comment by caiquecastro** [comment]
Is there a way to check if the document exists other than accessing a property?

In my code, I'm doing a:


```
// on my DocumentA class

public function getDocumentB()
{
try {
    $this->documentB->getName();

    return $this->documentB;
} catch (DocumentNotFoundException $e) {
    return new DocumentB;
}

```

But I don't like it.

**Comment by alcaeus** [comment]
You can either load references directly when running the query by priming references. This can be done using the `prime()` method on your query builder object, but it's not available when using the `findBy` or `findOneBy` methods in a repository. I would also recommend against it due to performance reasons.

There is also an event that is triggered whenever a proxy object could not initialized: [documentNotFound[(http://docs.doctrine-project.org/projects/doctrine-mongodb-odm/en/latest/reference/events.html#documentnotfound). In an event handler you can handle the missing document and prevent the exception from being thrown. However, you do not have access to the document containing the broken proxy (in your case the instance of `DocumentA`) due to the way proxies are built.

The last way is what you've done: initialize the proxy object before returning it.

**Comment by malarzm** [comment]
FWIW I was using

```
    public function doesReferencedItemExist()
    {
        try {
            if ($this->reference instanceof Proxy) {
                $this->reference->__load();
            } elseif ($this->reference === null) {
                return false;
            }
        } catch (DocumentNotFoundException $e) {
            return false;
        }
        return true;
    }
```

**Comment by caiquecastro** [comment]
Can I use the documentNotFound event the same way I create events like PostPersist or PostUpdate?

Example:

```
/**
 * @ODM\PostPersist
 * @ODM\PostUpdate
 */
public function someEvent()
{
    // PostPersist or PostUpdate triggered.
}
```

**Comment by alcaeus** [comment]
The syntax you described is what's known as a lifecycle callback, e.g. a method in your document class that will be invoked. Since the proxy loader won't have an entity to invoke this method on (we can't invoke the method on an uninitialized proxy), it's only available as a lifecycle event. You'll have to create an event subscriber to handle it: http://docs.doctrine-project.org/projects/doctrine-mongodb-odm/en/latest/reference/events.html#listening-to-lifecycle-events
