### ISSUE TITLE
Allow providing discriminatorClass as an option for embedded fields

### ISSUE THREAD

**Issue by TomiS** [doctrine/mongodb-odm#1512]
Current `mongodb-odm` implementation has two methods for defining class for mixed embedded objects. 1) store class name into the database in `_doctrine_class_name` or 2) use discriminator maps.

I believe these options are enough for many use cases but recently I've found them quite limiting for following reasons. Storing class name into the database will require difficult migration process whenever a class name changes even a bit. I think stuff like class names just shouldn't be in database because it causes all kinds of interesting refactoring and maintenance problems in the long run. Discriminator maps are better but their major flaw is that they cannot be dynamically configured even if they are used within a framework that supports nice configuration patterns (e.g. Symfony).

So here's my idea. Allow providing `discriminatorClass` as a configuration property for embedded fields like this:
```yaml
embedMany:
  tasks:
    discriminatorField: type
    discriminatorClass: My\Project\MyDiscriminator
```
Class MyDiscriminator would look something like this
```php
class MyDiscriminator implements Doctrine\ODM\DiscriminatorInterface
{
    /**
     * @param string $value content of the discriminatorField
     * @return string class name
     */
    public function resolve($value) {
        if ($value == 'special') {
            return 'My\Special\Class';
        }
        return 'My\Basic\Class';
    }
}
```
Any thoughts?

**Comment by malarzm** [comment]
Generally speaking I like the idea but I think the resolver/transformer/whaetver-we-name-it should work in both ways. Also I imagine that next request will be giving people ability to inject stuff into the resolver and I have no idea yet how to handle it, but maybe we should wait and see if it happens at all.

Also with introduction of such feature we should think about extracting discriminator value determining logic to some dedicated class as it grows bigger and bigger.

**Comment by TomiS** [comment]
@malarzm Yeah, I thought about this a bit more. Am I correct that even with this solution one wouldn't be able to use framework features such as Symfony dependency injection / configuration to inject stuff into the Discriminator/Resolver class. Is this purely because Doctrine classes and configurations are loaded somehow before (or outside) framework stuff? In that case you are right and this solution alone wouldn't do much good.

**Comment by TomiS** [comment]
At the moment I'm thinking if Doctrine ODM should allow setting the schema configuration from outside via public api. That could enable glue libraries such as DoctrineMongoDBBundle to take more responsibility in handling the configuration with all the features of the surrounding framework. But... I'm still not familiar enough with doctrine internals to actually be able to say if it's feasible. Just throwing some ideas.

**Comment by malarzm** [comment]
> Am I correct that even with this solution one wouldn't be able to use framework features such as Symfony dependency injection / configuration to inject stuff into the Discriminator/Resolver class.

In a way proposed - yes, you're correct. With only FQCN given Doctrine will need to instantiate resolver on its own and it has no idea about any services or containers.

> Is this purely because Doctrine classes and configurations are loaded somehow before (or outside) framework stuff?

Doctrine stuff is usually loaded by a framework, hence there's a bundle (or module for Zend etc.) which glues together ODM and framework of developer's choice. This glueing layer is responsible for passing your services into ODM - see repository factory or persistent collection factory.

> if Doctrine ODM should allow setting the schema configuration from outside via public api.

Well, theoretically there is [one](https://github.com/doctrine/mongodb-odm/blob/master/lib/Doctrine/ODM/MongoDB/Mapping/ClassMetadataInfo.php). Problem is that direct usage is quite cumbersome and I wouldn't recommend doing so on your own. Also any change we want (and can) introduce would be problematic because all glue libraries would need to tag along.

> I've noticed there are files like SymfonyFileLocator.php in Doctrine/common that make me wonder if there could be something to be improved in the hierarchy of responsibility considering config loading. Shouldn't that file, for example, be inside a Symfony bundle as it obviously is heavily Symfony related.

I'm not sure if I'm right as I can't recall how the file you're linking to is used, but it's possible that it's used ny all Doctrine bundles and that's why it's in doctrine/common.

> I'm thinking if there would be lots of configurability to gain by implementing configuration parsing inside DoctrineMongoDBBundle instead of this library and then passing the configuration down to the lower level libraries.

I'm sure there would be configurability gains but IMO they'd be outweighed by the fact that each library would have its own parsing and (as written before) it could be hard to maintain.

All in all, my view may be biased by current status quo so if you have any insights on how to improve please do not hesitate to share (or ping me on IRC), but I think that spreading resposibility of parsing configuration and building mapping information among glue libraries will bring more maintenance problems to the table than joy of using i.e. container parameters in configuration files.

**Comment by TomiS** [comment]
I just found this article about [Override Doctrine ODM mapping for Symfony FOSUserBundle
](http://blog.lavoie.sl/2015/01/symfony-override-doctrine-mapping.html) that provides a method for modifying Doctrine ODM schemas based on Symfony configuration.

I also just found about [ResolveTargetDocumentListener](http://docs.doctrine-project.org/projects/doctrine-mongodb-odm/en/latest/cookbook/resolve-target-document-listener.html)s that seems to solve the same issue too.

So now that I know about these, I think I'll close this ticket as redundant.
