### ISSUE TITLE
Sometime NumberLong, sometime NumberInt ?

### ISSUE THREAD

**Issue by chandon** [doctrine/mongodb-odm#1517]
I've got documents with different integer fields

I'm using mongo-odm 1.1.2. with mongodb 3.2.10

Some fields are stored in mongodb as NumberInt, and some other as NumberLong (even if the value is lower than 10 !)

Is there a solution to force NumberInt or NumberLong for a field ? Or why are some fields NumberInt and other NumberLong ?

**Comment by chandon** [comment]
I had multiple instance of php, some configured with php.ini directive : 

    mongo.native_long = 0 # NumberInt in mongo

and some with

    mongo.native_long = 1 # NumberLong in mongo

**Comment by malarzm** [comment]
@chandon glad you found out the culprit! Can I close the issue given culprit was the driver?

**Comment by chandon** [comment]
@malarzm yes thanks. Perhaps this should be somewhere in the doc...

**Comment by Steveb-p** [comment]
Doctrine ORM (or rather, DBAL) contains a list - matrix - of mapping types here: http://docs.doctrine-project.org/projects/doctrine-dbal/en/latest/reference/types.html#mapping-matrix

I believe ODM does not have an abstraction layer itself, since it is focused solely on Mongo, so it's type reference mirrors ORM page. See http://docs.doctrine-project.org/projects/doctrine-mongodb-odm/en/latest/reference/basic-mapping.html vs http://docs.doctrine-project.org/projects/doctrine-orm/en/latest/reference/basic-mapping.html#doctrine-mapping-types.

I can see the point of @chandon, I was also looking for a reference myself at some point. Especially when I was new to the whole Mongo thing, and I couldn't figure out for example what type should I use to store an associative array.

**Comment by malarzm** [comment]
For me http://docs.doctrine-project.org/projects/doctrine-mongodb-odm/en/latest/reference/annotations-reference.html is always serving as a good reference point. As always I;m really open to all documentation improvements however I'd rather keep driver specific things out of it especially given the driver has changed and eventually we'll use only it in 2.0

**Comment by Steveb-p** [comment]
I guess so :) I actually never noticed that the now-deprecated annotations contained more specific mapping info. That makes my point invalid :) Thanks.

**Comment by chandon** [comment]
i think that ODM, even if it doesn't have such an attraction layer as ORM, should not be dependent of driver configuration... So it should handle MongoInt32 / MongoInt64 by itself. But perhaps this discussion comes to late with new php-mongodb drivers...

**Comment by alcaeus** [comment]
Maybe @jmikola can shed some more light on the details of this, but neither doctrine/mongodb-odm nor doctrine/mongodb mess around with 32-bit or 64-bit integers. So, when you map a field with `@Field(type="int")` (or the deprecated `@Int`), the [IntType](https://github.com/doctrine/mongodb-odm/blob/b93cae185896cfeeb7c4b6dcef5d9c7da82be1a2/lib/Doctrine/ODM/MongoDB/Types/IntType.php#L31) will cast your value to an integer before sending it on the way to the driver. The driver then converts it to the appropriate BSON type (either BSON INT or BSON LONG, depending on the `native_long` setting mentioned above) and stores it in the database. When the document is read at a later date, the driver again converts the BSON types to primitive integers, unless a BSON LONG is encountered and `mongo.long_as_object` is enabled.

Now, technically, there isn't a problem with having some numbers stored as BSON INT and some as BSON LONG as both are converted to int when a document is returned by the driver. It might get complicated on 32-bit systems, but I'm not even going to think about that.

As for the new driver, it doesn't expose any 32- or 64-bit BSON type classes, so I'd assume that it handles integer types appropriately.

**Comment by chandon** [comment]
@alcaeus it's a problem when you share your mongo DB with other ODM like morphia (java). Morphia needs explicit types, and it throws an exception when trying to cast BSON INT to Long or BSON LONG to Integer.

**Comment by alcaeus** [comment]
Ah, yes, that makes sense. @jmikola how does the new driver handle this? Maybe we should provide mapping types for 64-bit and 32-bit integers after all to make sure this can be properly taken care of.

**Comment by jmikola** [comment]
The new driver does not have any classes to represent 32-bit and 64-bit integers.

When serializing PHP to BSON on a 64-bit platform, we append a 32-bit or 64-bit BSON integer based on the value (just like the server). On a 32-bit platform, we always append as 32-bit because the size of a PHP integer is already limited to 32-bits. The relevant macro is [here](https://github.com/mongodb/mongo-php-driver/blob/1.2.8/src/bson.c#L40).

When deserializing BSON to PHP, we generally attempt to convert the BSON integer to a PHP integer. The only edge case is if we encounter a 64-bit BSON integer on a 32-bit platform and it's value exceeds the range of what we can represent in a 32-bit signed integer. In that case, we throw an exception (see: [this macro](https://github.com/mongodb/mongo-php-driver/blob/1.2.8/phongo_compat.h#L146)).

**Comment by malarzm** [comment]
I think we can't do much for ODM's 1.x version and in 2.0 we'll rely on what's happening in new driver.
