### ISSUE TITLE
Why i have to define inversedBy to Bi-Directional Reference documents

### ISSUE THREAD

**Issue by alu** [doctrine/mongodb-odm#1571]
I read [this](http://docs.doctrine-project.org/projects/doctrine-mongodb-odm/en/latest/reference/bidirectional-references.html) document but i can't understand why i have to define inversedBy annotation.

The BlogPost document of This sample has reference of a User document. So i think we can get User from instance of BlogPost even without define inversedBy to BlogPost.

``` php
<?php

/** @Document */
class BlogPost
{
    // ...

    /** @ReferenceOne(targetDocument="User", inversedBy="posts") */
    private $user;
}

/** @Document */
class User
{
    // ...

    /** @ReferenceMany(targetDocument="BlogPost", mappedBy="user") */
    private $posts;
}
```

Could someone tell the reason to me?

**Comment by malarzm** [comment]
> why i have to define inversedBy annotation.

What "inversedBy" annotation you're mentioning? Is it about having `$posts` property in `User`? Most probably you can live without it but, also probably, you may want to have access to posts of the user from that level.

**Comment by alu** [comment]
@malarzm 

Thank you for response!

I mentioned to `$user` in `BlogPost` in the sample.

I understand **Why `$posts` in `User` wants mappedBy?** It is for access to user's posts such as `$user->getPosts()`.

And also understand **Why `$user` in `BlogPost` wants `@ReferenceOne`**. It is for access to blog post's user such as `$blogPost->getUser()`.

But i can't understand **Why `@ReferenceOne` of `$user` in `BlogPost` wants `inversedBy`?**.

Actually, if i don't define `inversedBy` also i can access to blog post's user.

I am sorry that the question is difficult to understand...

Thanks.

**Comment by alcaeus** [comment]
`inversedBy` is not used in ODM, but it's there because ORM has it.

In ODM, specifying `mappedBy` marks the relationship as inverse (the wording may be confusing, think of it of the inverse to `owning` which is the default), meaning the document the relationship is mapped on doesn't know directly about the related documents.

Let's take the User <-> Post relationship:
```
/** @Document */
class BlogPost
{
    // ...

    /** @ReferenceOne(targetDocument="User") */
    private $user;
}
```

This is a owning relationship where the BlogPost document knows the user. In the database, it would look like this:
```
{
    _id: ...
    user: {
        $ref: 'user',
        $id: ...
    }
}
```

Now for the user document:

```php
/** @Document */
class User
{
    // ...

    /** @ReferenceMany(targetDocument="BlogPost", mappedBy="user") */
    private $posts;
}
```

`posts` is an inverse relationship, meaning the user document does not know directly about the posts a user has written:
```
{
    _id: ...
    username: ...
}
```

Of course, you could store the reference directly, but that would require you to update the user document every time a post was created. It would also continuously grow in size, which is discouraged in MongoDB because it can lead to fragmentation.

Let's say you would leave out `inversedBy`, and created a new blog post, you'd have to update both references:
```php
$post = new BlogPost($user);
$user->addBlogPost($post);
```

The same would happen when you delete a blog post: you'd have to manually remove it from the `posts` property in the User object and then store it. To avoid this kind of housekeeping, you can use inverse references.

I hope this helps to clear up some confusion.

**Comment by malarzm** [comment]
> Actually, if i don't define inversedBy also i can access to blog post's user.

Ah thanks for clarification, now I see :) The `inversedBy` you're mentioning is in fact superfluous (or at least I can't recall anything relying on it as it's marked internally as owning side anyway), usage of it stems most probably from ORM which I believe requires to know the other side of a relationship

**Comment by alu** [comment]
@alcaeus 

> Let's say you would leave out inversedBy, and created a new blog post, you'd have to update both references:

I think if i leave out `mappedBy`, save each other's reference.  So `mappedBy` is important For data rationality.

It seems to me to work in the same way as i don't define.

> inversedBy is not used in ODM, but it's there because ORM has it.

I can understand why necessary it in ORM case!

**Comment by alu** [comment]
@malarzm 

namely, inversedBy is not necessary in ODM?
If so, my brain will be clear!

**Comment by alcaeus** [comment]
@alu yes, `inversedBy` is not necessary in ODM. It's not used at all. The way you've implemented it using `mappedBy` is how it's done in ODM 👍

**Comment by alu** [comment]
@alcaeus Thanks! I'm happy!
