### ISSUE TITLE
GridFS can't use php streams

### ISSUE THREAD

**Issue by metanav** [doctrine/mongodb-odm#1578]
I have a simple File document.
```
/** @ODM\Document */
class File
{
    /** @ODM\Id */
    private $id;

    /** @ODM\File */
    private $file;
}
```
When I set $file as data stream the File.files is created but the File.chunks does not save any file.

```
$stream = "data://text/plain, hello world";
$fp = fopen($stream, "r");
$data = ['file' => $fp]; 
// $data = ['file' => $stream]; // this is not working either
$file = new File();
$file->setFile($data['file']);
```

Why I am doing this?
I have a textarea in a form which submits data as content which I want to save in GridFS as a file.

Note: The php client has ability to read stream.
```
public mixed MongoGridFS::storeFile ( string|resource $filename [, array $metadata = array() [, array $options = array() ]] )

filename : Name of the file or a readable stream to store.

```

**Comment by alcaeus** [comment]
While `MongoGridFS` has support for streams, the library we built on top (doctrine/mongodb) does not. At this time, there is no option but to store the contents in a temporary file and read from that.

This will be different in 2.0. I don't have much information on that yet, except that the current working branch I have for the switch to the new MongoDB already had its GridFS support removed in order to rebuild it from the ground up. However, it will be similar to the handling in mongodb/mongodb, which only works with streams ([link to documentation](https://docs.mongodb.com/php-library/master/tutorial/gridfs/)).

**Comment by metanav** [comment]
Thanks @alcaeus 
Any (tentative) ETA for the 2.0?

**Comment by alcaeus** [comment]
> Any (tentative) ETA for the 2.0?

Not really, no. I've started porting ODM to the new driver but have had a busy few months with almost no time for ODM, at least not to the point where I can sit down and think about all the BC breaks I'm introducing. I'm hoping to at least get an Alpha version out this year.

Now that you mention it, I'll write down the roadmap I have in my head and post it on our blog so people using ODM have a bit more information of what's going on and what the challenges are.
