### ISSUE TITLE
ReferenceMany : Store reference and a label

### ISSUE THREAD

**Issue by psa-gbellencontre** [doctrine/mongodb-odm#1619]
Hello
I created a ReferenceMany relation in order to add actors to a movie. It works perfectly, but I'm looking for a solution to store the actor name with the reference.
I just need a quick way to get the actors names without calling the Actor Collection
So I'd like to store the name with the reference.

Is it possible, and how ?
Thanks

Grégory

**Comment by alcaeus** [comment]
Out of the box, no. I've started working on that feature in #1527, but decided to move it to the 2.0 milestone because it may require some reference changes. At this time, I wouldn't hold my breath to get this in a 1.x release.

As for a workaround, you may be able to magically update the owning object by gaining access to the owner in a `postLoad` event handler (using the `getParentAssociation` method in `UnitOfWork`) and updating the owning object. The name won't be stored on the reference but in a separate field since you don't have access to the generated DBRef object.

**Comment by psa-gbellencontre** [comment]
Ok, thanks for your quick answer !
