### ISSUE TITLE
Unhelpful error message when using objects instead of scalars

### ISSUE THREAD

**Issue by stampycode** [doctrine/mongodb-odm#1633]
Try:

    $dm->getRepository(MyThing::class)->findBy(['badField' => 'abc']);

Throws:

    zero-length keys are not allowed, did you use $ with double quotes?

Would like to see:

    Field 'badField' is not defined in the schema, OR an empty search resultset.

Trace:

    [0] => ../vendor/doctrine/mongodb/lib/Doctrine/MongoDB/Cursor.php(550) [anonymous_function]
    [1] => ../vendor/doctrine/mongodb/lib/Doctrine/MongoDB/Cursor.php(550) rewind MongoCursor
    [2] => ../vendor/doctrine/mongodb/lib/Doctrine/MongoDB/Cursor.php(726) Doctrine\MongoDB\{closure} Doctrine\MongoDB\Cursor
    [3] => ../vendor/doctrine/mongodb/lib/Doctrine/MongoDB/Cursor.php(551) retry Doctrine\MongoDB\Cursor
    [4] => ../vendor/doctrine/mongodb-odm/lib/Doctrine/ODM/MongoDB/Cursor.php(528) rewind Doctrine\MongoDB\Cursor
    [5] => () rewind Doctrine\ODM\MongoDB\Cursor
    [6] => ../vendor/doctrine/mongodb-odm/lib/Doctrine/ODM/MongoDB/Cursor.php(650) iterator_to_array
    [7] => ../vendor/doctrine/mongodb-odm/lib/Doctrine/ODM/MongoDB/DocumentRepository.php(185) toArray Doctrine\ODM\MongoDB\Cursor

**Comment by malarzm** [comment]
@stampycode is this code made-up or it actually comes from your app? Asking because using unmapped field is a valid use-case which should not break anything and the exception message you mention was seen by me usually when working with hash/collection type and having bad value put there.

**Comment by stampycode** [comment]
@malarzm the code above is all from the `doctrine/mongodb-odm` codebase - I'm using it in a Symfony2 codebase, which has a YAML config describing the dataset.
If I remove this line, I get no error.

    $dm->getRepository(MyThing::class)->findBy(['badField' => 'abc']);

Now that my codebase has had some other changes I can't reproduce the issue, so might as well close this. Not sure what's going on.

**Comment by malarzm** [comment]
Feel free to reopen in case you'd have more details!

**Comment by stampycode** [comment]
So turns out I got this error by accidentally passing an array into the search criteria for a field expecting a single value:

    $owner = $repo->findBy(['owner' => $user]);

I was using `findBy` instead of `findOneBy` to populate the `$user` object - resulting in it being an array - even an array of one value triggers the exception shown above.

I'm hoping this means we can craft a more helpful error message now? 😬

**Comment by stampycode** [comment]
@malarzm I'm not able to re-open the ticket... 😑

**Comment by malarzm** [comment]
@stampycode reopened and scheduled for 1.2. Also if you feel like, try digging into ODM and fixing by yourself, this will greatly speed things up :)

**Comment by stampycode** [comment]
> Can you share exactly what the value of $user is in this case? 
@jmikola sure, it's an instance of a document, stored by reference in the containing class that `$repo` represents.

**Comment by jmikola** [comment]
It looks like I misunderstood the issue on the first read.

When the exception occurred, was `$user` definite an empty array (i.e. criteria matched nothing)? If not, does the criteria possibly match multiple documents, or would it always match exactly one user (i.e. single-element array with a numeric `0` key)?

@malarzm: If `owner` is a mapped reference, then this could have been caused by [`DocumentPersister::prepareDbRefElement()`](https://github.com/doctrine/mongodb-odm/blob/f7379e4eeaffcd33d83fb4b0fcc4ccce1acb8a4e/lib/Doctrine/ODM/MongoDB/Persisters/DocumentPersister.php#L1425)'s handling of unexpected input, or [`DocumentManager::createDBRef()`](https://github.com/doctrine/mongodb-odm/blob/f7379e4eeaffcd33d83fb4b0fcc4ccce1acb8a4e/lib/Doctrine/ODM/MongoDB/DocumentManager.php#L679) returning an empty array for an empty input argument.

**Comment by stampycode** [comment]
I'm certain that the `$user` car had a single document in it - but it was in an array instead of just the bare document.

**Comment by alcaeus** [comment]
I've tried to reproduce this in 1.2.x (using `alcaeus/mongo-php-adapter` as polyfill which [replicates the exception in question](https://github.com/alcaeus/mongo-php-adapter/blob/ae806ac488c021dfe1be5af2abf0ce62376058f7/lib/Mongo/MongoCollection.php#L987)) with the test below, but couldn't reproduce it. @stampycode if you can create a reproducer, please open a pull request with it and I'll investigate. In the meantime, I'll close this since we can't reproduce it.

---

```php
use Doctrine\ODM\MongoDB\Mapping\Annotations as ODM;
use Doctrine\ODM\MongoDB\Tests\BaseTest;
use Documents\User;

class GH1633Test extends BaseTest
{
    public function testFindWithWrongType()
    {
        $user = new User();
        $document = new GH1633Document();
        $document->owner = $user;
        $this->dm->persist($user);
        $this->dm->persist($document);
        $this->dm->flush();

        $this->assertCount(1, $this->dm->getRepository(GH1633Document::class)->findBy(['owner' => $user]));
        $this->assertCount(0, $this->dm->getRepository(GH1633Document::class)->findBy(['owner' => [$user]]));

        $this->assertCount(0, $this->dm->getRepository(GH1633Document::class)->findBy(['scalar' => $user]));
        $this->assertCount(0, $this->dm->getRepository(GH1633Document::class)->findBy(['scalar' => [$user]]));
    }
}

/** @ODM\Document */
class GH1633Document
{
    /** @ODM\Id */
    public $id;

    /** @ODM\Field */
    public $scalar;

    /** @ODM\ReferenceOne(targetDocument=User::class) */
    public $owner;
}
```
