### ISSUE TITLE
Doctrine/ODM/MongoDB/Cursor.php 528 rewind

### ISSUE THREAD

**Issue by ahrrikis** [doctrine/mongodb-odm#1637]
Hi, 
in Doctrine/ODM/MongoDB/Cursor.php 528 $this->baseCursor->rewind(); cannot be excecuted if the collection is empty, as go around I propose:
 if($this->baseCursor->count()>0){
                $this->baseCursor->rewind();
        }

The logged Message is Read timed out after reading 0 bytes, waited for 30.000000 seconds, it is only fired if collection is empty.

**Comment by jmikola** [comment]
Please share some details about your PHP environment. Specifically:

 * What is your PHP version?
 * What MongoDB extension is installed and what is its version? (e.g. `ext-mongo`, `ext-mongodb`)
 * If you're using `ext-mongodb`, what version of `alcaeus/mongo-php-adapter` are you using?
 * What versions of `doctrine/mongodb` and `doctrine/mongodb-odm` are installed?

**Comment by ahrrikis** [comment]
- PHP 5.6.30 
- MongoDB 2.6.12
- Akeneo 1.6.16 called from src/Pim/Bundle/VersioningBundle/Doctrine/MongoDBODM/VersionRepository.php ->getOneLogEntry( ...
- doctrine/mongodb-odm-bundle: 3.2.0

It's not about the collection, its about the query result is empty, then somehow it tries and tries and fails.

**Comment by malarzm** [comment]
@ahrrikis please also post whether you're using `ext-mongo` or `ext-mongodb` as PHP extension for connecting to Mongo and the version you're on.

**Comment by ahrrikis** [comment]
ext-mongo 1.6.14

**Comment by jmikola** [comment]
> doctrine/mongodb-odm-bundle

The ODM requirement for that version of the bundle is [`^1.1`](https://github.com/doctrine/DoctrineMongoDBBundle/blob/3.2.0/composer.json#L15), which may be satisfied by multiple versions. What tags of `doctrine/mongodb-odm` _and_ `doctrine/mongodb` are installed?

> Akeneo 1.6.16 called from src/Pim/Bundle/VersioningBundle/Doctrine/MongoDBODM/VersionRepository.php ->getOneLogEntry()

This is the first I've heard of Akeneo, but I was only able to find https://github.com/akeneo/pim-community-dev/tree/master/src/Pim/Bundle/VersioningBundle, which does not include the ODM class you're referencing. [Setting up the Hybrid Storage MySQL/MongoDB](https://docs.akeneo.com/1.6/developer_guide/installation/setup_hybrid_storage_mysql_mongo.html) is the only page in Akeneo's docs that I found referring to MongoDB, but it doesn't mention the class above.

I assume if this error is only occurring within a full application, you will not be able to provide code we can execute to reproduce the exception.

What is the full backtrace for the exception?

> It's not about the collection, its about the query result is empty, then somehow it tries and tries and fails.

Since [`Doctrine\ODM\MongoDB\Cursor`](https://github.com/doctrine/mongodb-odm/blob/1.1.6/lib/Doctrine/ODM/MongoDB/Cursor.php) decorates a [`Doctrine\MongoDB\Cursor`](https://github.com/doctrine/mongodb/blob/1.6.0/lib/Doctrine/MongoDB/Cursor.php), the method in question would be [`Doctrine\MongoDB\Cursor::rewind()`](https://github.com/doctrine/mongodb/blob/1.6.0/lib/Doctrine/MongoDB/Cursor.php#L546). That method does support retrying (the number of attempts is configurable) if a MongoCursorException or MongoConnectionException is thrown by the driver.

The "Read timed out..." error message originates in [`php_mongo_io_stream_read()`](https://github.com/mongodb/mongo-php-driver-legacy/blob/1.6.14/io_stream.c#L344) and the message is used to construct an exception in [`php_mongo_cursor_throw()`](https://github.com/mongodb/mongo-php-driver-legacy/blob/d4ce6992164893d185e9d1538c48857479d1554e/cursor_shared.c#L523) while processing a network reply (or lack thereof).

That said, I see no reason that a socket error would be related to an empty query result (i.e. query criteria matched no documents). Have you considered that there only _appears_ to be no query result because the query is executing too slowly and cannot return its first batch of results to the driver within 30 seconds? 30 seconds is coincidentally the default `socketTimeoutMS` for [`MongoClient::__construct()`](http://php.net/manual/en/mongoclient.construct.php). If the driver is giving up on a slow-running query, I can guarantee that the query is still running on the server (you can check with [`db.currentOp()`](https://docs.mongodb.com/manual/reference/method/db.currentOp/)) and subsequent retry attempts will only result in additional queries building up on the server.

**Comment by ahrrikis** [comment]
Hej, 
i can't reproduce this, the work around fixed it on the production environment. The exception log for this and stack trace is not available anymore. 
On the other hand an check if the set is empty, would not cause that much load. 

Can be closed.

**Comment by jmikola** [comment]
> i can't reproduce this, the work around fixed it on the production environment.

I'm glad this is resolved for you.

> The exception log for this and stack trace is not available anymore.

That a bit unfortunate, as I don't think we'll ever get to the root cause of the problem.

> On the other hand an check if the set is empty, would not cause that much load.

For the record, the workaround suggested in the first post does have the potential to incur noticeable overhead. Calling [`Doctrine\MongoDB\Cursor::count()`](https://github.com/doctrine/mongodb/blob/1.6.0/lib/Doctrine/MongoDB/Cursor.php#L139) actually results in its own round trip to the server to execute a separate [`count`](https://docs.mongodb.com/manual/reference/command/count/) command. Additionally, the count and query are two operations and thus their results may not always be consistent (i.e. the number or results for the cursor may not equate to what the `count` command returns).
