### ISSUE TITLE
Will there be an alternative to isIndexed etc. in 2.0

### ISSUE THREAD

**Issue by josefsabl** [doctrine/mongodb-odm#1645]
Methods that help with finding out whether the query is indexed are marked as deprecated and will be removed in 2.0. Will there be any alternative?

**Comment by malarzm** [comment]
We don't have such plans. Problems is that current implementation is wrong as for instance compound indexes are not handled correctly. Also MongoDB introduced partial indexes which would add more code to maintain on our side. In my opinion it's better to not provide such functionality than to provide one that is misleading: it wouldn't be good if ODM claimed the query is using an index but in reality it's not.

**Comment by malarzm** [comment]
So the solution would be to run query on one's own with `.explain()` to see if it's using indexes, if `$or` clauses are handled correctly and whatnot.

**Comment by alcaeus** [comment]
I agree with @malarzm here. Re-implementing the index selection logic of the server in ODM for informational purposes isn't feasible, especially since it depends on the server version used. For example, with [index intersection](https://docs.mongodb.com/manual/core/index-intersection/) a query could be completely covered by indexes even if there isn't a single index that covers the query. However, index intersection isn't available for all index combinations, so there would be considerable overhead in reimplementing that logic.

FWIW, all of those reasons mentioned are the reason why we decided to remove the feature for 2.0 - it just makes more sense to run `explain()` as @malarzm mentioned.

**Comment by josefsabl** [comment]
Thanks for explanation guys.
