### ISSUE TITLE
Upserting a field of an existing Document with null does not update that field

### ISSUE THREAD

**Issue by Spunc** [doctrine/mongodb-odm#1671]
Given a Document with a certain `_id` exists in the database and has `someField` set to a non-null value.

If I create a new Object of that Document class, set its `_id` to that of the existing Document but set `someField` to  `null`, persisting that object does not set `someField` to `null` but leaves it as it was.

Setting `someField` of the new Object to a non-null value will update that Document.

Thus, the update query excludes fields that are set to `null`. I would expect it to be possible to update an existing Document's field with `null` during an upsert operation.

**Comment by alcaeus** [comment]
Have you tried setting the `nullable` option on the field in question? That should fix your issue. That said, upserts should `$unset` non-nullable fields if they are `null`. Could you provide a failing test case for us? You can look at [existing tests](https://github.com/doctrine/mongodb-odm/tree/master/tests/Doctrine/ODM/MongoDB/Tests/Functional/Ticket) for guidance.

**Comment by Spunc** [comment]
Thanks @alcaeus! Setting the `nullable` option on the field solved the problem.

However, upserts don't `$unset` non-nullable fields to `null`, as my tests shows.

**Comment by alcaeus** [comment]
That's good to hear. I'll take a look at the failing tests shortly and fix this issue in 1.2.1. Thank you for your help!

**Comment by alcaeus** [comment]
I really apologise for the long delay here, but I completely lost track of the issue. First of all, thank you for providing the test case. I looked at the issue in question and it is easily fixable, but I'm not sure if we want to do so.

To explain, here's a quick summary on how we treat `null` as field value:
- When inserting documents, we skip all fields with a `null` value unless they have the `nullable` option set.
- When updating documents, we `$unset` all fields with a `null` value that don't have the `nullable` option set. `nullable` fields get their value set to `null`

Upserting documents thus should somehow respect both behaviors, which technically means calling `$unset` on fields with a `null` value. However, we don't know if the field value is `null` because it should be unset from the document or whether it just wasn't filled out because its value is not known and the upsert operation shouldn't modify it. In my opinion, both are valid use cases, but we can't satisfy both. This is why I'm not sure if this is something we can fix in 1.2 or whether it has to wait for 2.0 because it would require mapping changes (e.g. a flag to indicate how to deal with `null` values).

**Comment by malarzm** [comment]
> However, we don't know if the field value is null because it should be unset from the document or whether it just wasn't filled out because its value is not known and the upsert operation shouldn't modify it.

I think for 1.x we should keep the current behaviour (otherwise it would be a BC break if people would start losing data because of `null`s). Also cross-referencing with #1425 as this is something we should support.

**Comment by jmikola** [comment]
If inserts and updates both result in `null` values being set for nullable-mapped fields, it sounds like they can both get the same behavior. For non-nullable fields that have `null` values, we exclude them from an insert document and use `$unset` for updates/upserts.

Note: MongoDB offers a [`$setOnInsert`](https://docs.mongodb.com/manual/reference/operator/update/setOnInsert/#up._S_setOnInsert) operator if we needed conditional logic for upserts resulting in an insert, but I don't think that's needed.

> However, we don't know if the field value is null because it should be unset from the document or whether it just wasn't filled out because its value is not known and the upsert operation shouldn't modify it.

If I'm reading this correct, you're asking about a case where we might not want to update fields because ODM can't discern if they've changed since a new document object was instantiated. I'd argue that if we're doing an insert/upsert with a newly created document (i.e. no changeset) we should assume that the user wants the post-write document in MongoDB to reflect the state of the document object being persisted and flushed. To do otherwise would require us to differentiate between uninitialized properties and those that were explicitly assigned with `null` (I don't think that's possible).



I'm of the opinion that upserts should follow insert semantics. The end result of the write operation should be that the

**Comment by alcaeus** [comment]
@jmikola correct - differentiating between uninitialized properties and explicit `null` values is impossible. I agree with your opinion that the behavior should be the same as for insert, even though some might see it as a BC break.

@Spunc I prepared a fix for this issue this morning but need to clean up a test. I hope to push this to the 1.2.x branch over the weekend. We're still tracking a different issue for 1.2.2, but I'm hoping to (finally) release a fix for your issue within a week.

**Comment by alcaeus** [comment]
After managing to pick @jwage's brain for a little bit, turns out we all got it backwards. The original idea was to preserve data already in the database, so writing `null` values shouldn't happen in `$upsert` queries. Thus, the behavior for non-nullable fields is correct but incorrect for fields with a `nullable` attribute set. Thus, I'll change the tests and pull request to fix this accordingly in 1.2.2.

As for overriding `null` values, your safest bet is to fetch data and then update it in the database, even at the cost of a hydration cycle. I agree your test cases may seem valid, but you typically don't know what other fields may already have been written to the database, so it's a good idea not to touch them.

We may consider adding a switch to enable this behavior (either on a per-field or per-document basis) in 2.x somewhere, but for now this is something we can't (and won't) fix. We will however address the inconsistency between nullable and non-nullable fields.
