### ISSUE TITLE
Accessing referenced embedded documents causes error (missing proxy)

### ISSUE THREAD

**Issue by Garinn** [doctrine/mongodb-odm#1686]
Hi,

I recently upgraded to 3.4.1 (doctrine-odm-bundle, using 1.2 of doctrine-odm) and found that doctrine no longer generates proxies for embedded documents (see #430).

This is a problem in my case:

* I use embedded documents to create nodes of a tree-like data structure
* other parts of the application reference specific nodes (using referenceOne / referenceMany)
* trying to access one of these referenced embedded documents now causes an error because Doctrine tries to load a non-existent proxy file

Any ideas?

Downgrading doctrine-odm to 1.1.5 fixed the issue for the time being.

**Comment by malarzm** [comment]
Without any steps to reproduce or code to look at I'd say that referencing embedded documents was never supported and I have no clue how it could be working in the first place :)

**Comment by Garinn** [comment]
Honestly, I was a bit suprised to see it work. Here is some very simple example code to reproduce the behaviour:

```
/** @Document */
class Tree
{
    /** @EmbedMany(targetDocument="Node") */
    private $nodes = array();
    // ...
}

/** @EmbeddedDocument */
class Node
{
    /** @Id */
    private $id;
    // ...
}

/** @Document */
class NodeCondition
{
    /** @ReferenceOne(targetDocument="Node") */
    private $node;
    // ...
}
```

Basically, referencing embedded documents worked fine as long as the embedded document had its own id. This creates a regular DBRef in MongoDB, using the document's class name as the $ref part, even though no collection with that name exists.

I have no clue how this gets resolved but a freshly hydrated instance of NodeCondition would correctly point to the specified instance of Node.

Let me know if there is anything else I can do to help with this issue.

**Comment by malarzm** [comment]
> referencing embedded documents worked fine as long as the embedded document had its own id. This creates a regular DBRef in MongoDB, using the document's class name as the $ref part

Can't back up my guess with code as I can't run anything ATM, but here goes my shot: (probably) the `Node` you were referencing was always already loaded by ODM (i.e. it was present in `UnitOfWork`). Due to the fact the `Node` had a mapped identifier, it could be looked up with it even though it was an embedded document. Later, when `Proxy` was being resolved the first thing that ODM tries is to lookup the document internally in `UnitOfWork` and, accidentally, there was a hit. I think this is how the `Proxy` was resolving correctly, if you could check that theory with a not loaded `Node` (so just by fetching `NodeCondition` and trying to access `$node` from there) that would be great.

**Comment by Garinn** [comment]
That makes perfect sense and seems to be correct. In my tests, accessing the referenced `Node` only worked if the corresponding `Tree` was already loaded.

Soo ... basically, I was relying on an unintended side effect of the ODM, not an actual feature?

**Comment by malarzm** [comment]
> Soo ... basically, I was relying on an unintended side effect of the ODM, not an actual feature?

Sorry to say, but yes :)

**Comment by Garinn** [comment]
Guess I have a lot of technical debt to work through, then. Thanks for your help and input!
