### ISSUE TITLE
Remove N number of documents

### ISSUE THREAD

**Issue by pablomoreno61** [doctrine/mongodb-odm#1690]
Hi,

Using mongo odm 1.1.6 and I'm trying to remove last 10 messages from a mongodb collection, using a query like this:
        
```
$this->getDocumentManager()->createQueryBuilder(Message::class)
            ->remove()
            ->field('userId')->equals((int) $userId)
            ->limit($count)
            ->sort('createdAt', 'ASC')
            ->getQuery()
            ->execute();
```

But this query is removing all the userId messages instead of just the limited 10 messages.

I've printed the getQuery->debug() information, ant it's returning me the following:

```
Array
(
    [type] => 6
    [limit] => 10
    [sort] => Array
        (
            [created_at] => 1
        )

    [query] => Array
        (
            [user_id] => 780997
        )

    [newObj] => Array
        (
        )

)
```

I think it should accept the criteria, limit and sorting properties as MongoDB does.

**Comment by malarzm** [comment]
According to [MongoDB docs](https://docs.mongodb.com/v3.4/reference/method/db.collection.remove/#query-considerations)

> By default, remove() removes all documents that match the query expression. Specify the justOne option to limit the operation to removing a single document.

And I can't see anything there that limit/sort would work. Am I missing something?

**Comment by pablomoreno61** [comment]
You are right. So, you can close ticket as an issue, but its a bit weird that doctrine doesn't complaint about that, isn't it?

I've replaced my code by the following:

`
        $mongoUserIds = $this->getDocumentManager()->createQueryBuilder(Message::class)
            ->select(array('userId'))
            ->field('userId')->equals()
            ->limit($count)
            ->sort('createdAt', 'ASC')
            ->getQuery()
            ->execute();

        if (empty($mongoUserIds)) {
            return 0;
        }

        return $this->getDocumentManager()->createQueryBuilder()
            ->remove()
            ->field('userId')->in($mongoUserIds)
            ->getQuery()
            ->execute();
`

**Comment by malarzm** [comment]
> its a bit weird that doctrine doesn't complaint about that, isn't it?

That's true, but if MongoDB would one day introduce skip/limit, we'd need to know upfront which version are you running to allow such usage, and forbid it for older databases. This would also apply to all other features that currently MongoDB is releasing (I'm looking at aggregation stuff) and that would be horrendous to maintain. Due to that we're providing a builder than can build (almost) anything and it's up to user to know whether such query can be executed by his/her MongoDB or not.

Offhand, to correctly format you can use triple backticks, I've edited your posts so they look better :)

**Comment by pablomoreno61** [comment]
oks thanks!
