### ISSUE TITLE
how to set immortal forever

### ISSUE THREAD

**Issue by GraysMile** [doctrine/mongodb-odm#1809]
|    Q        |   A
|------------ | -----
| Version     | x.y.z

### Support Question

I foreach the query`s results, and do something(each document maybe cost long time). Then i will get error "(MongoDB\\Driver\\Exception\\RuntimeException(code: 43): Cursor not found,", i think the cursor`s immortal is not forever, how can i fix it?

**Comment by Steveb-p** [comment]
@GraysMile you should not make a cursor immortal unless it's necessary.

Check http://php.net/manual/en/mongocursor.immortal.php before continuing.

Making a cursor immortal is as simple as calling `Builder->immortal()` (argument is `true` by default). Since it's basically causing the ODM to call `MongoCursor->immortal()` at some point during execution, there is not much ODM can do more.

**Comment by malarzm** [comment]
I agree with @Steveb-p, hope this answers your question @GraysMile. In case it doesn't, please follow up.

**Comment by GraysMile** [comment]
thx, i got it
