### ISSUE TITLE
Clean stages in aggregate builder when execute the query

### ISSUE THREAD

**Issue by Strick3r** [doctrine/mongodb-odm#1822]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | yes/no
| BC Break    | yes/no

#### Summary

I would like to reuse the aggregate builder in the same instance, but when execute a query, not clean the stages, then there are acumulated in the next queries.

Can be possible to clean there when execute or make a function to remove a stage or all stages?

Thanks

**Comment by alcaeus** [comment]
For now I would suggest creating a new aggregation builder. When I wrote it I didn't think of using it like the query builder where it would create a query object for you. In hindsight I probably should have, but I haven't 🤷‍♂️

I'll keep this open and consider it for 2.0 since it's a BC break, I'm just not sure yet what route to take here.

**Comment by alcaeus** [comment]
After giving this some thought, I've decided that we'll leave the API like this for 2.0. While the aggregation builder doesn't return a query object like the query builder does, the behavior is the same for both: fetching a query from the query builder does not reset the builder instance, this has to be done manually.

Since it's relatively easy to fetch a new builder object (be it aggregation builder or query builder), I don't see a lot of sense to reset the builder instance when the aggregation pipeline is executed.
