### ISSUE TITLE
Aggregation builder $indexStats with discriminator fields mapping

### ISSUE THREAD

**Issue by aturki** [doctrine/mongodb-odm#2018]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | no
| Version     | 1.2.8

#### Summary
Aggregation builder $indexStats with discriminator fields mapping

#### Current behavior
The aggregation builder fails to execute $indexStats stage when a discriminatorField is used in the class definition with error "$indexStats is only valid as the first stage in a pipeline." (ref: https://docs.mongodb.com/manual/reference/operator/aggregation/indexStats/#behavior)

#### How to reproduce
```
// Parent.php
/**
 * @ODM\InheritanceType("SINGLE_COLLECTION")
 * @ODM\DiscriminatorField("someField")
 *
 * @ODM\Document()
 *
 */

 class Parent
 {
 }

// Child.php 
/**
 * @ODM\Document()
 *
 */
 class Child extends Parent
 {
 }

// SomeService.php
$builder = $documentManager->createAggregationBuilder(Child::class);
$result = $builder->indexStats()->execute()->toArray(); // <- Fails here as the $indexStat is not the first stage of the pipeline (due to discriminator)
```

#### Expected behavior

IndexStats pipeline should be executed even when the collection contains a discriminator field. 
As a technical suggestion: maybe reordering the aggregation pipeline stages before executing them could solve this ? Any guidance on how to attack this (for a PR) is appreciated ;)

**Comment by alcaeus** [comment]
Could you please post the output of `$builder->indexStats()->getPipeline()`? I suspect that the culprit is in https://github.com/doctrine/mongodb-odm/blob/4acb36955163b20e1ac3241c5fe354ea24337691/lib/Doctrine/ODM/MongoDB/Aggregation/Builder.php#L219..L221 - we presend a `$match` stage containing the appropriate filters, but may not be allowed to do so. In fact, we check for a `$geoNear` stage, so we might want to check for an `$indexStats` stage as well.

**Comment by aturki** [comment]
@alcaeus, that's exactly it. Here is the output of `$builder->indexStats()->getPipeline()`
```
array (2) [
    array (1) [
        '$match' => array (1) [
            'type' => string (21) "my-discriminator-value"
        ]
    ]
    array (1) [
        '$indexStats' => stdClass (0)
    ]
]
```
