### ISSUE TITLE
logger callable will not work

### ISSUE THREAD

**Issue by fengjunhui** [doctrine/mongodb-odm#2026]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | no
| Version     | 1.2.8

When i create document manager by "DocumentManager::create($connection, $configuration)",and i only set logger callable on $config.But the log callable should be setted on $connection if that work.When creating document manager, dm's construct founction would not set $configuration into $connection included log callable.And i think it is a BUG.

**Comment by fengjunhui** [comment]
#1354

**Comment by alcaeus** [comment]
This is not an issue. The connection part of the `Configuration` instance will be passed when creating a new connection, but will not be used to overwrite any settings on an existing connection. This is because it is your responsibility to pass the correct options when creating the connection. ODM cannot assume that you'll want connection options overwritten, especially since the same connection may be reused for multiple document managers, in which case this needs to be kept separate.

Calling `DocumentManager::create(null, $configuration)` will apply settings, but `DocumentManager::create($connection, $configuration)` will not. Note that it's possible to pass the same `Configuration` instance to the connection and to the document manager, but as said before, you'll have to do this yourself when manually creating a connection.
