### ISSUE TITLE
Ensure query filters for replacement-style updates include shard keys for MongoDB 4.2

### ISSUE THREAD

**Issue by jmikola** [doctrine/mongodb-odm#2027]
[SERVER-39158](https://jira.mongodb.org/browse/SERVER-39158) describes a change for MongoDB 4.2 whereby replacement-style updates target the update to a shard by the replacement document. Starting in 4.2, these updates will instead be targeted by the query document.

To my knowledge, ODM does not make extensive use of replacement-style updates. I'm not too concerned about the query builder, as it would be up to users to handle this there. Apart from that, are replacement-style updates used when persisting a new document in conjunction with the `upsert` option, or do we simply use normal inserts there? It'd possible this ticket won't require any changes within ODM, but I wanted to open this ticket just to be sure.

If changes are required, I think a portable solution may be to ensure the shard key is included in _both_ the query filter and replacement document.

For additional context, I can quote a reply I left on an internal ticket:

> The behavioral change [in SERVER-39158] is simply:
>
> * Previously, replacement-style `update` commands would be routed to shards by the [`update`](https://docs.mongodb.com/manual/reference/command/update/#update-command-behaviors) document (i.e. replacement document).
> * After SERVER-39158, those same update commands will be routed by the `filter` document.
>
> The scenario described in SERVER-39158's description demonstrates a case where an `update` could return successfully and not match anything, when the desired behavior would be to raise an ImmutableField error. While that seems harmless, if we revise that scenario to include an `upsert: true` option on the `update` command then we risk inserting a new document instead of raising an error.
>
> AFAICT, the relevant audit for ODMs and any other libraries would be any case where a replaceOne (with or without an upsert) might be executed internally. We can probably forego any query builders that allow users/applications to craft their own replacements, as that's no different than a user calling `replaceOne()` directly through a driver.

**Comment by alcaeus** [comment]
Right now, the shard key is always added to the query part when writing a document through `DocumentPersister`, see https://github.com/doctrine/mongodb-odm/blob/a50624c38534a3f238353c83c12fb268eee61281/lib/Doctrine/ODM/MongoDB/Persisters/DocumentPersister.php#L354 and https://github.com/doctrine/mongodb-odm/blob/a50624c38534a3f238353c83c12fb268eee61281/lib/Doctrine/ODM/MongoDB/Persisters/DocumentPersister.php#L1384. When using the query builder, users themselves have to make sure to add the shard key to the query manually: since there's no one document being updated, we can't infer the shard key from other information.

From what I can see, ODM does not use replacement-style updates at all.

**Comment by alcaeus** [comment]
Closing here - I don't see where we need this. We can always revisit once testing with MongoDB 4.2 starts.
