### ISSUE TITLE
Can Doctrine's ODM reference one document without declaring type?

### ISSUE THREAD

**Issue by JonathanHolvey** [doctrine/mongodb-odm#2040]
### Feature Request

|    Q        |   A
|------------ | :----:
| New Feature | yes
| RFC         | ?
| BC Break    | ?

#### Summary

I'm using Doctrine with Symfony 4. I can see in the documentation for Doctrine's ODM references that a referenceMany relationship can store different types of documents in references by omitting the targetDocument option:

```php
/* @Document */
Class User
{
    /* @ReferenceMany(targetDocument="Account") */
    private accounts = [];
}
```
becomes

```php
/* @Document */
Class User
{
    /* @ReferenceMany */
    private accounts = [];
}
```

 It seems that the same can't be achieved with the referenceOne relationship. When I use referenceOne without the targetDocument option, I get a mapping exception:

> Class '' does not exist

Ideally I'd like to be able to use the mappedBy and inversedBy options so that the Account document owns the relationship, and is able to reference either a User or a Company, which share some properties. The following doesn't work, but is there a way to achieve what it represents?

```php
/* @Document */
class User
{
    /* @ReferenceMany(targetDocument="Account", mappedBy="owner") */
    private $accounts = [];
}

/* @Document */
class Company
{
    /* @ReferenceMany(targetDocument="Account", mappedBy="owner") */
    private $accounts = [];
}

/* @Document */
class Account
{
    /* @ReferenceOne(inversedBy="accounts") */
    private $owner;
}
```

I created this issue in response to a comment by @malarzm on my StackOverflow question on the same subject. https://stackoverflow.com/questions/56626419/can-doctrines-odm-reference-one-document-without-declaring-type

**Comment by alcaeus** [comment]
You can omit the `targetDocument` property for all references as long as you don't use `storeAs="id"` in the mapping. You can find an example in the tests: https://github.com/doctrine/mongodb-odm/blob/a50624c38534a3f238353c83c12fb268eee61281/tests/Doctrine/ODM/MongoDB/Tests/DocumentRepositoryTest.php#L77. The document in question uses a `ReferenceOne` mapping without `targetDocument` property.

I'm not sure about the specifics of your case, but maybe you could try creating a small reproducer for us to investigate? Thanks!

**Comment by JonathanHolvey** [comment]
> You can omit the targetDocument property for all references as long as you don't use storeAs="id" in the mapping

I just got round to testing this as I'm using `@ReferenceOne` successfully in the same project without specifying `targetDocument` or `storeAs` properties. However, my use case requires a bi-directional reference, requiring `@ReferenceOne(inversedBy="accounts")`, which results in an error:

> Target document must be specified for owning/inverse sides of reference: App\Document\Account::target

Removing the `inversedBy` property to leave a uni-directional reference results in the error reported above:

> Class '' does not exist

**Comment by alcaeus** [comment]
Thanks for the update! I’ll take a closer look at this next week 👍

**Comment by alcaeus** [comment]
Sorry for the delay here, this slipped under my radar - good thing the bot reminded me (again).

I've taken another look, and we have a test covering this. You can see such a reference in the [`Documents\FavoritesUser`](https://github.com/doctrine/mongodb-odm/blob/56408ed68687a6d826230881d87720dccf54f4e4/tests/Documents/Functional/FavoritesUser.php#L32) document, which is used in a functional test: https://github.com/doctrine/mongodb-odm/blob/56408ed68687a6d826230881d87720dccf54f4e4/tests/Doctrine/ODM/MongoDB/Tests/Functional/FunctionalTest.php#L615.

The error you are seeing when you use `inversedBy` is expected, but that is literally the only time the ODM cares about `inversedBy`. I didn't want to remove it for 2.0 as there are some things we could do with it in the future. However, you don't need to put it in.

With all that said, on to figure out what causes your problem. When you have a relationship without a target document (regardless of whether it is a reference or an embedded document), ODM stores the class name of the object in a field named `_doctrine_class_name`. The name of this field can be changed using the `discriminatorField` annotation. If you don't want to store the class name, you can assign the class a discriminator value using the `DiscriminatorValue` mapping on the class, or you can specify a `DiscriminatorMap` on the class or the reference mapping. This is explained in the [reference documentation](https://www.doctrine-project.org/projects/doctrine-mongodb-odm/en/2.0/reference/reference-mapping.html#mixing-document-types).

When loading a document with an untargeted reference, ODM will read the value of the discriminator field, find the FQCN if there is a discriminator map involved, then create a proxy object for that class. The error you're describing hints at there being a document that doesn't have a discriminator value in the reference. There are two ways of dealing with this: if you know that all references without a discriminator value are of a certain type (e.g. because it was a targeted reference before), you can define a default discriminator value. There is an example in the documentation I've linked above. The other option is to look for all documents that have a reference without a discriminator value and update them accordingly.
