### ISSUE TITLE
dbRefWithDb multiple dbs

### ISSUE THREAD

**Issue by Romaxx** [doctrine/mongodb-odm#2046]
Hello,
Is it possible to use dbRefWithDb to reference collection from another database ?
Currently if I reference document managed by another documentManager, it throw an error "A new document was found through a relationship that was not configured to cascade persist operations".

DB1:
- Collection 1: refA

DB2:
- Collection 1: refB

how refA can reference refB easily ?
Thanks

**Comment by alcaeus** [comment]
Whether you store your references as ID references, `dbRef`, `dbRefWithDb` or the new `ref` doesn't make a difference since ODM will always use mapping information to know where to fetch data for a referenced document. The storage strategy matters when you're accessing the references from a separate application that doesn't use ODM.

As for your problem at hand, are both documents managed by the same entity manager?

**Comment by Romaxx** [comment]
both documents are managed by distinct documentManager because I use cluster per tenant strategy, each db have their own host (https://fr.slideshare.net/mongodb/securing-mongodb-to-serve-an-awsbased-multitenant-securityfanatic-saas-application) I have created a superclass DocumentManagerFactory which serve the right documentManager instance according to the class and account used. Currently I use two string fields in document to reference a document in another db (db name and object id, class is fixed), but it's painful, I would like to integrate the mechanism in doctrine.

**Comment by alcaeus** [comment]
I'm thinking how we can better ensure this besides through documentation, but a referenced document needs to be managed by the same document manager as the referencing document, otherwise the error you encountered will occur. Referencing a document managed by another document manager simply isn't possible.

I'm not sure I understand your reasoning for using multiple document managers, but either way, referencing documents between them isn't supported. Please also be aware that references across databases while possible are only partially supported by MongoDB, e.g. the `$lookup` aggregation pipeline stage only supports looking up documents stored in the same database. If the databases in questions are stored in separate clusters, then you'll be even more out of luck as there is no option to reliably join these databases anymore.

**Comment by Romaxx** [comment]
Thank you, I understand the limitation.
