### ISSUE TITLE
Logging page is obsolte

### ISSUE THREAD

**Issue by TheHett** [doctrine/mongodb-odm#2089]
|    Q        |   A
|------------ | -----
| Version     | 2.0.0

### Support Question

I want to find a way to use logging in ODM 2.0
How I understand this page is obsolete:
https://www.doctrine-project.org/projects/doctrine-mongodb-odm/en/2.0/reference/logging.html

If possible, tell me how to use the PSR-3 logger?

**Comment by SenseException** [comment]
Truly a very outdated part in the docs. Thank you for pointing that out. I've created #2090 for removing that part from the 2.x documentation.

As for the question about using a psr-3 logger, I'm not sure myself. We probably need a way to introduce psr-3.

**Comment by TheHett** [comment]
Thanks!
Is there any way to enable logging using ODM?
Information about this will not be superflous in the documentation :)

**Comment by alcaeus** [comment]
The Symfony Bundle for ODM contains a PSR-3 logger: https://github.com/doctrine/DoctrineMongoDBBundle/blob/master/APM/PSRCommandLogger.php. Not sure why we didn't add it to ODM itself, but here we are

**Comment by alcaeus** [comment]
For the sake of completeness, I don't think that logging any command as it was sent to the database is a good idea. You may want to filter this, customise log output, redact some data, and so on. I think you're way better off doing this yourself.

I'm closing this as the issue at hand (e.g. obsolete documentation) has been fixed in a PR and will be removed from the docs once they are re-deployed (which happens periodically).

**Comment by TheHett** [comment]
Why not add CommandLoggerInterface to the documentation on that page instead of deleting?

**Comment by alcaeus** [comment]
Because the interface is mainly provided for the bundle. The actual functionality is described in the MongoDB extension docs: https://www.php.net/manual/en/mongodb.tutorial.apm.php. There are a few downsides to using command subscribers, mainly because you will be notified for all commands sent on the client object, which may be reused by multiple processes on the same machine.
