### ISSUE TITLE
Metadata stored, queried but not populated

### ISSUE THREAD

**Issue by webdevilopers** [doctrine/mongodb-odm#2145]
|    Q        |   A
|------------ | ------
| Version     | 2.0.3

I added metadata as an embedded document:

```xml
<doctrine-mongo-mapping xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                                                 xmlns="http://doctrine-project.org/schemas/odm/doctrine-mongo-mapping"
                                                 xsi:schemaLocation="http://doctrine-project.org/schemas/odm/doctrine-mongo-mapping
                        http://doctrine-project.org/schemas/odm/doctrine-mongo-mapping.xsd">

<gridfs-file name="DefectImage" bucket-name="defect_images">
    <id field-name="id" type="bin_uuid" />
    <length />
    <chunk-size />
    <upload-date />
    <filename field-name="filename" />
    <metadata target-document="DefectImageMetadata" field-name="metadata" />
</gridfs-file>
</doctrine-mongo-mapping>
```

```xml
<doctrine-mongo-mapping xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                                                 xmlns="http://doctrine-project.org/schemas/odm/doctrine-mongo-mapping"
                                                 xsi:schemaLocation="http://doctrine-project.org/schemas/odm/doctrine-mongo-mapping
                        http://doctrine-project.org/schemas/odm/doctrine-mongo-mapping.xsd">

<embedded-document name="DefectImageMetadata">
    <field field-name="mimeType" type="string" />
</embedded-document>
</doctrine-mongo-mapping>
```

The metadata is stored in the collection. I can also query for it:

```php
$imageRepository->findOneBy(['metadata.mimeType' => 'image/jpeg']);
```

But the Document property is not populated. Other properties e.g. `chunkSize` or `uploadDate` work correctly.

Possibly related to:
* https://github.com/doctrine/mongodb-odm/issues/2141
* https://github.com/doctrine/mongodb-odm/pull/1989

**Comment by malarzm** [comment]
@webdevilopers is this bug specific to the XML mapping? Any chance you could write a failing test case?

**Comment by webdevilopers** [comment]
Are there any exiting tests for XML mapping that could help me getting started?

**Comment by malarzm** [comment]
Here is test: https://github.com/doctrine/mongodb-odm/blob/master/tests/Doctrine/ODM/MongoDB/Tests/Functional/Ticket/GH774Test.php and here are mappings: https://github.com/doctrine/mongodb-odm/tree/master/tests/Doctrine/ODM/MongoDB/Tests/Functional/Ticket/GH774 :)

**Comment by webdevilopers** [comment]
Ok, GH123 stands for Github and number of issue I guess.
I will return to that project next week. I will give it a try then! :)

**Comment by malarzm** [comment]
> Ok, GH123 stands for Github and number of issue I guess.

Correct :)

**Comment by alcaeus** [comment]
I changed the mapping driver tests to use a different field name (by changing the property name for annotations and the `field-name` property for XML mappings), and the resulting mapping file is the same. This eliminates the XML mapping driver as the culprit (which was the case in #2141). Given that, we can assume that the `DefaultGridFSRepositoryTest` tests apply to XML mappings as well, even though they use annotation mappings rather than XML.

You've already cross-referenced #1989, which fixed an issue with metadata storage that slipped through the cracks due to insufficient testing. Since the `findOneBy` call returns documents, I would also assume that the metadata is stored correctly when uploading the file through the repository.

One option is that the hydrator refuses to hydrate the embedded document. This can be caused by invalid data in the document. In this case, it would help to see the document as it's stored in the database. The best course of action is to run the `findOneBy` in the MongoDB shell and posting the resulting document here. This would allow us to evaluate why the data is not properly hydrated. Furthermore, can you confirm that the document in question was written by this version of ODM or created differently (e.g. by a different application or migrated from the legacy document structure with arbitrary fields in the file document)?

**Comment by webdevilopers** [comment]
I just returned to the project. When we tested the first time we had a "mimeType" field inside the metadata. This has now changed to "contentType" and the issue no longer exists.
We didn't anything else so I can only guess that there was mismatch with the mapping.

Everything seems to work as expected now. :+1:

**Comment by alcaeus** [comment]
That’s good to know, thanks for the update!
