### ISSUE TITLE
Priming fields for aggregation query builder

### ISSUE THREAD

**Issue by anyx** [doctrine/mongodb-odm#2173]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | yes
| BC Break    | no

#### Summary

Looks like right now there is no way to use fields priming for aggregation queries (with hydration enabled). It would be nice feature, I think. Or it's possible somehow?

**Comment by alcaeus** [comment]
What is your use-case? Priming was added since there's no way to use joins in queries. For aggregation pipelines, the `$lookup` operator provides this functionality, so I'd recommend you use that whenever you know that you're going to need referenced documents.

I'll also add that if you find yourself in the need to prime references to avoid n+1 problems, your schema might need improving, as the references should be changed to embedded documents instead. I'm aware that this does not always work or satisfy every use-case, but in general you should prefer embedded documents over references and primers.

**Comment by anyx** [comment]
Use-case pretty common, I think: for example, I need to calculate some statistic data per user (or just `$project` document to different format) and return collection of these elements like a regular document's collection with avoiding n+1 situations.

I never use hydration for aggregation query builder's before and always done it manually. I thought, since there a way to hydrate my aggregation results and with them like with regular documents, priming can be used for them too

**Comment by alcaeus** [comment]
In this case, you'd `$lookup` your reference and map it as `@EmbedOne` or `@EmbedMany` in the aggregation result document. This negates the need for lookup as the "priming" will be performed in the original aggregation pipeline.

**Comment by anyx** [comment]
@alcaeus ok, thank you for advice!
