### ISSUE TITLE
Add support for a multiple field type

### ISSUE THREAD

**Issue by smilesrg** [doctrine/mongodb-odm#2341]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | yes
| BC Break    | no

#### Summary

I noticed that field could be just one type. But in MongoDB field could be any type. Use-case example: I need to provide a filed, if property price includes taxes. If yes, that field value is equal to `true`. If no, then field value contains an object with the tax description (amount, currency or percentage).

**Comment by smilesrg** [comment]
I have found such workaround:

```php

namespace App\Document;

use Doctrine\ODM\MongoDB\Mapping\Annotations as ODM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ODM\Document
 */
class Hotel
{
    /**
     * @ODM\Field(type="raw")
     *
     * @Assert\AtLeastOneOf({
     *     @Assert\EqualTo(true),
     *     @Assert\Type(HotelTaxNotIncluded::class)
     * })
     * @Assert\Valid
     */
    protected bool|array|HotelTaxNotIncluded $hotelTax;

    public function getHotelTax(): bool|HotelTaxNotIncluded
    {
        if (is_array($this->hotelTax)) {
            $hotelTax = new HotelTaxNotIncluded();

            $hotelTax->setAmount($this->hotelTax['amount']);

            if (!empty($this->hotelTax['percent'])) {
                $hotelTax->setPercent($this->hotelTax['percent']);
            }

            if (!empty($this->hotelTax['currency'])) {
                $hotelTax->setPercent($this->hotelTax['currency']);
            }

            $this->hotelTax = $hotelTax;
        }

        return $this->hotelTax;
    }
```

However, `@EmbedOne` annotation still can't be used.

Property `$hotelTax`  has typehinting of `bool`, `HotelTaxNotIncluded` and `array` as values from Mongo comes as array.
`@ODM\Field(type="raw")` - defines a field of any type
`@Assert\AtLeastOneOf` annotation validates that value is either `true` or a type of `HotelTaxNotIncluded` class.
Return type of `public function getHotelTax()` is `bool` or `HotelTaxNotIncluded`, we don't expect array to be returned.
And inside the method, we are checking if property is array. If it is, we are initializing a `HotelTaxNotIncluded` object and assigning this object to a property, instead of an array.

Hope that helps someone.

**Comment by malarzm** [comment]
Arguably you'd be better of using `EmbedOne` with `nullable=true` - if there's no tax then `hotelTax` is `null`, or a value object otherwise. `?HotelTax` sounds to me way more sane than `bool|array|HotelTaxNotIncluded` from types' perspective.

Anyway, what you're describing can be achieved with custom types and that's the encouraged way to go. Built-in type intersection sounds like a lot of trouble for little gain.

**Comment by smilesrg** [comment]
There are other use cases, for example, a field could be a string type or an object. That's can't be solved using `EmbedOne` with `nullable=true` as string value should be one from set of values. Anyway, thank you for the suggestion!

**Comment by malarzm** [comment]
Theoretically `string|EmbedOne` sounds doable, but technically we'd need to support full type intersection and that can go out of hand easily with somebody wanting `bool|EmbedOne|EmbedMany|ReferenceOne` because why not :)

Given ODM allows you to define custom types I honestly think this is better to be done in userland, where you'll have knowledge about what types do come into play, which handle first and so on.
