### ISSUE TITLE
Performance penalty getClassMetadata

### ISSUE THREAD

**Issue by sirian** [doctrine/mongodb-odm#2355]
## Problem

Each call to `$documentManager->getClassMetadata($class)` causes ClassMetadataFactory to resolve real class again and again. This causes huge performance penalty when documentManager actively used.

https://github.com/doctrine/mongodb-odm/blob/9ca6f5f9b0198da8ee930796255b4714c75db07d/lib/Doctrine/ODM/MongoDB/DocumentManager.php#L300

https://github.com/doctrine/mongodb-odm/blob/9ca6f5f9b0198da8ee930796255b4714c75db07d/lib/Doctrine/ODM/MongoDB/Mapping/ClassMetadataFactory.php#L68

## Tests

I made some tests. 10000 calls to `getClassMetadata` consumes **~14.7ms**

```php
$start = microtime(true);
for ($i = 0; $i < 10000; $i++) {
    $dm->getClassMetadata(User::class);
}
var_dump(microtime(true) - $start);
```

## Tests with cache

Now I extend DocumentManger and add caching, and run tests again. 10000 iterations consumes **0.76ms** (20x times faster!)
```php
class DocManager extends DocumentManager
{
    private array $classMetadataCache = [];

    public function getClassMetadata($className): ClassMetadata
    {
        return $this->classMetadataCache[$className] ??= parent::getClassMetadata($className);
    }
}
```

**Comment by franmomu** [comment]
Thanks for reporting! can you please try it with the `2.3.x` branch?

Class name resolvers were removed in https://github.com/doctrine/mongodb-odm/pull/2304 (apparently there was cache in the class name resolving) https://github.com/doctrine/mongodb-odm/blob/9ca6f5f9b0198da8ee930796255b4714c75db07d/lib/Doctrine/ODM/MongoDB/DocumentManager.php#L204

**Comment by alcaeus** [comment]
To follow up on this, we do have a few benchmarks for performance critical stuff. @sirian if you feel up for it, you can add a performance test in the `benchmark` in a PR to 2.2.x. The test should repeatedly fetch metadata from the document manager for a non-proxy class and a proxy class (to test class name resolution). We'd expect mean performance to be very similar after a number of iterations, since only the first call is expected to be slower.

As mentioned by @franmomu, this was removed in 2.3.x now that doctrine/persistence can take care of this. When building the new proxy system, I realised that we'd have to make extensive changes to doctrine/persistence to account for the different proxy naming scheme, which I postponed due to the workload involved. I'd expect this to me significantly more efficient in 2.3.x, but in case we do spot performance issues there, we might want to fix them in doctrine/persistence before releasing 2.3.x. Since ODM is the only manager currently proxies other than those from doctrine/common, there's no real performance testing going on of the logic in doctrine/persistence.

Please let us know if you're interested in making the changes or if you need help with it.

**Comment by malarzm** [comment]
I do believe this is fine now with caching in place.
