### ISSUE TITLE
Consider setting field to `null` for upserts

### ISSUE THREAD

**Issue by ivan-wolf** [doctrine/mongodb-odm#2431]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | unknown
| Version     | `2.3.1`

#### Summary

The behavior in question was introduced with #2318, I believe.

#### Current behavior

Consider the following scenario:

1. A document has `foo: bar` set in MongoDB.
2. In code, the respective document (unmanaged) has `foo: null` set.
3. When persisted, the value in MongoDB is still `foo: bar`.

#### Expected behavior

When the (unamanged) document is persisted, the value in MongoDB is set to `foo: null`.

**Comment by malarzm** [comment]
If my memory serves me right we don't update fields to null with upsert to allow partial upserts. Sadly this look like yet another issue that could be solved by a proper upsert API which we still don't have :/

**Comment by ivan-wolf** [comment]
Hi @malarzm. Thank you for your reply!

I had a quick look around but didn't find out the rationale behind "partial upserts". Can you please elaborate on that?

The way I see it, with PHP becoming more type-safe, it's not a likely use case that a document/object is created with only some properties set, with the goal to only have these properties/fields updated in MongoDB 🤔

Having said that, I'm probably missing something, so I'm looking forward to your thoughts on the matter.

Also, how do you envision a "proper upsert API"? Maybe I could help with that.

**Comment by malarzm** [comment]
> I had a quick look around but didn't find out the rationale behind "partial upserts". Can you please elaborate on that?

Currently it's perfectly fine to do something like (keeping it simple, not gonna worry about accessors, validation, et al)

```
$doc = new Document();
$doc->id = new Id($_GET['id']);
$doc->name = 'upserted';
// every other property Document may have is not gonna be changed to null after flush
$dm->persist($doc);
$dm->flush();
```

> The way I see it, with PHP becoming more type-safe, it's not a likely use case that a document/object is created with only some properties set, with the goal to only have these properties/fields updated in MongoDB thinking

That's true for a lot of new applications (but not all). But there's a lot of apps that are older :) Of course they should be actively maintained and upgraded, but reality often differs. The most important part here is that we must not change the current behaviour as it may lead to data loss for our users. If anybody had code written like I did above they would end up with every other property of `Document` nulled.

> Also, how do you envision a "proper upsert API"? Maybe I could help with that.

Sadly there is no vision yet :) All I know is that we'd like to give users explicit control over `$setOnInsert` (and then handle it somehow after the insertion does happen so the document is in correct state if that'll be feasible). That'll most probably require new method `upsert` in DocumentManager` but maybe we could somehow do it with current `persist`.

**Comment by pietereggink** [comment]
We experienced the same problem, why is it not allowed to upsert a column from an existing value to a null value?

File: PersistenceBuilder.php
Line: 249.php
Version: 2.4.2

```
// Fields with a null value should only be written for inserts
if ($new === null) {
    if ($mapping['nullable'] === true) {
        $updateData['$setOnInsert'][$mapping['name']] = null;
    }

    continue;
}
```

What is the reason why this code is added?

I think this should be the same as on line 147 

```
if ($new === null) {
    if ($mapping['nullable'] === true) {
        $updateData['$set'][$mapping['name']] = null;
    } else {
        $updateData['$unset'][$mapping['name']] = true;
    }

    continue;
}
```

Also the documentation is incorrect, (// Fields with a null value should only be written for inserts) but if you check method prepareUpdateData than the behavior is different. From my point of view this is a bug.

**Comment by malarzm** [comment]
> What is the reason why this code is added?

For the exact reason I've outlined in the previous comment:

> The most important part here is that we must not change the current behaviour as it may lead to data loss for our users. If anybody had code written like I did above they would end up with every other property of Document nulled.

**Comment by alcaeus** [comment]
To explain the motivation for this, let's first look at `null` values that you may have in a mapped property. if `nullable` is false, you're indicating that a `null` value should not be written to the database. That's why the second code excerpt uses `$unset` to remove a field with a `null` value from the document, while explicitly setting it to `null` if the field is marked as `nullable`.

When using an upsert, `null` suddenly has two different meanings: the value could be `null`, as in "I want to have a `null` value in the database, or it could be `null` as in "I didn't bother working with this field and don't want to change the value in the database". That's why we're using `$setOnInsert` in the first code excerpt if the field is `nullable`. When the upsert results in a new document being created, we can safely write a `null` value to the document. When the upsert results in an existing document being updated, we don't know which meaning the `null` value has, and so we chose to err on the side of caution as misinterpreting the `null` value would result in data loss.

In a future world where a document class used only typed properties without default values, we could use reflection to check whether a value was set and interpret the behaviour based on that, with a `null` value meaning that the value was explicitly set, and the property having no value meaning that we should not touch the field in the document on updating.

I understand that this behaviour is a bit strange, but be aware that changing this would constitute a major BC break that requires careful consideration to make sure we're not causing data loss for users. With that in mind, I'm closing the ticket as there are currently no plans for a 3.x version, and the persistence layer needing a significant overhaul before we could even tackle such a change.
