### ISSUE TITLE
Too few arguments error thrown for Doctrine\ODM\MongoDB\PersistentCollection - Constructor

### ISSUE THREAD

**Issue by teamore** [doctrine/mongodb-odm#2505]
### BC Break Report

|    Q        |   A
|------------ | ------
| BC Break    | yes
| Version     | 2.4.0

#### Summary

When sending requests to a running api-platform interface of a Symfony (v6.1.12, php8.2.1) application from an ubuntu instance (5.15.0-60-generic) within docker (v20.10.22) similar to this one:

http://localhost/api/posts?limit=20

I keep retrieving server errors 500 with an error message stating Too few arguments to function Doctrine\\ODM\\MongoDB\\PersistentCollection::__construct(), 0 passed in \/var\/www\/html\/vendor\/doctrine\/mongodb-odm\/lib\/Doctrine\/ODM\/MongoDB\/PersistentCollection\/DefaultPersistentCollectionFactory.php on line 16 and exactly 3 expected .

I receive this error message for every request against the api-platform from within my docker container running on Ubuntu 22.04.1 LTS.

#### Previous behavior

Result sets could be retrieved from mongo database with a request to api-platform:
http://localhost/api/posts/?limit=20&page=1

#### Current behavior

Retrieval of existing mongodb datasets with identical request results in a missing arguments exception:

[Too few arguments to function Doctrine\\ODM\\MongoDB\\PersistentCollection::__construct()](https://stackoverflow.com/questions/75524330/too-few-arguments-to-function-doctrine-odm-mongodb-persistentcollection-co)

More reproduction steps provided here:
(https://stackoverflow.com/questions/75524330/too-few-arguments-to-function-doctrine-odm-mongodb-persistentcollection-co/75524331#75524331)

**Comment by alcaeus** [comment]
Can you post the mapping of the field that is causing this? The method in question creates an instance of the collection class that's to be used underneath. This would be an `ArrayCollection` by default but can be changed by using the `collectionClass` option on any `ReferenceMany` or `EmbedMany` association mapping. I'm also wondering what broke this in 2.4.x, as I don't see any changes to this logic between 2.3.x and 2.4.x.

**Comment by malarzm** [comment]
Here goes nothing:

> Too few arguments to function Doctrine\ODM\MongoDB\PersistentCollection::__construct(), 0 passed in /var/www/html/vendor/doctrine/mongodb-odm/lib/Doctrine/ODM/MongoDB/PersistentCollection/DefaultPersistentCollectionFactory.php on line 16 and exactly 3 expected .

This would mean that somehow `PersistentCollection::class` needs to be created, which would mean either a really strange bug or a misconfiguration. The fact that ODM 2.4.0 exhibits a problem while earlier versions do not points me to #2411 as that's something (well, the only thing) that has an influence on `collectionClass` since its inception. So most probably OP has a property typed as `PersistentCollection` and autoconfiguration kicked in. `PersistentCollection` should not be the type of a property as it's ODM-specific detail.

But that's just a guess, we'll never know unless OP comes back :)
