### ISSUE TITLE
Calling takeSnapshot() when clearing PersistentCollection

### ISSUE THREAD

**Issue by megazoll** [doctrine/mongodb-odm#470]
There is ``takeSnapshot()`` call: https://github.com/doctrine/mongodb-odm/blob/master/lib/Doctrine/ODM/MongoDB/PersistentCollection.php#L564. So when I call ``clear()`` next ``getDeleteDiff()`` returns an empty array.

Is this behaviour correct?

**Comment by malarzm** [comment]
I believe the behaviour is correct, as `clear()` is scheduling collection for deletion and `$unset` will be issued instead of removing elements from it (which would be the case if snapshot would be left as `CollectionPersister` uses `getDeleteDiff` and doing both things is obviously not wanted behaviour).
