### ISSUE TITLE
Reference to inherited documents returns a proxy object of parent class instead of proper child

### ISSUE THREAD

**Issue by vmattila** [doctrine/mongodb-odm#562]
I hit the slightly buggy behavior of inheritance and references once again. In fact, I asked about this in Stack Overflow last year - but happily did a workaround and forgot it. SO question can be found from http://stackoverflow.com/questions/11545751/why-a-function-call-in-doctrines-proxy-object-points-to-parent-object-instead-o

If @ReferenceOne points to the inheritance parent document, the getter returns a proxy object of the parent instead of the child.

@jmikola asked for a test case in SO, it will be available in a minute in my fork. I will cross-refer it here.

**Comment by Wirone** [comment]
I had the same issue (getting not initialized proxy instead of related entity) in ORM. If this is proper place to share example code I can do it later.

In my case `fetch="EAGER"` on relation definition in parent entity did the trick.

**Comment by malarzm** [comment]
Closing the issue since simple references are not intended to work with discriminators as [stated in docs](http://docs.doctrine-project.org/projects/doctrine-mongodb-odm/en/latest/reference/reference-mapping.html#simple-references). Also as per @jwage [comment](https://github.com/doctrine/mongodb-odm/pull/1038#issuecomment-87233315) we will start throwing exceptions in such case soon.

**Comment by malarzm** [comment]
And to cross link issue about throwing exception: https://github.com/doctrine/mongodb-odm/issues/1124

**Comment by jmikola** [comment]
![](http://www.reactiongifs.com/wp-content/uploads/2013/05/serious-thanks.gif)
